/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { TrendingControllerFindActiveParams } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get active trending topics
 */
export const trendingControllerFindActive = (
  params: TrendingControllerFindActiveParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({ url: `/api/v1/trending`, method: 'GET', params, signal });
};

export const getTrendingControllerFindActiveQueryKey = (
  params?: TrendingControllerFindActiveParams,
) => {
  return [`/api/v1/trending`, ...(params ? [params] : [])] as const;
};

export const getTrendingControllerFindActiveQueryOptions = <
  TData = Awaited<ReturnType<typeof trendingControllerFindActive>>,
  TError = unknown,
>(
  params: TrendingControllerFindActiveParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof trendingControllerFindActive>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTrendingControllerFindActiveQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof trendingControllerFindActive>>> = ({
    signal,
  }) => trendingControllerFindActive(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof trendingControllerFindActive>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TrendingControllerFindActiveQueryResult = NonNullable<
  Awaited<ReturnType<typeof trendingControllerFindActive>>
>;
export type TrendingControllerFindActiveQueryError = unknown;

/**
 * @summary Get active trending topics
 */

export function useTrendingControllerFindActive<
  TData = Awaited<ReturnType<typeof trendingControllerFindActive>>,
  TError = unknown,
>(
  params: TrendingControllerFindActiveParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof trendingControllerFindActive>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTrendingControllerFindActiveQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Add a trending topic (admin/webhook)
 */
export const trendingControllerAddTopic = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/trending`, method: 'POST', signal });
};

export const getTrendingControllerAddTopicMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof trendingControllerAddTopic>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof trendingControllerAddTopic>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['trendingControllerAddTopic'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof trendingControllerAddTopic>>,
    void
  > = () => {
    return trendingControllerAddTopic();
  };

  return { mutationFn, ...mutationOptions };
};

export type TrendingControllerAddTopicMutationResult = NonNullable<
  Awaited<ReturnType<typeof trendingControllerAddTopic>>
>;

export type TrendingControllerAddTopicMutationError = unknown;

/**
 * @summary Add a trending topic (admin/webhook)
 */
export const useTrendingControllerAddTopic = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof trendingControllerAddTopic>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof trendingControllerAddTopic>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getTrendingControllerAddTopicMutationOptions(options);

  return useMutation(mutationOptions);
};
