/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary SSE stream for real-time updates (per-user filtered)
 */
export const realtimeGatewayEvents = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/realtime/events`, method: 'GET', signal });
};

export const getRealtimeGatewayEventsQueryKey = () => {
  return [`/api/v1/realtime/events`] as const;
};

export const getRealtimeGatewayEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof realtimeGatewayEvents>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof realtimeGatewayEvents>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRealtimeGatewayEventsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof realtimeGatewayEvents>>> = ({ signal }) =>
    realtimeGatewayEvents(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof realtimeGatewayEvents>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type RealtimeGatewayEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof realtimeGatewayEvents>>
>;
export type RealtimeGatewayEventsQueryError = unknown;

/**
 * @summary SSE stream for real-time updates (per-user filtered)
 */

export function useRealtimeGatewayEvents<
  TData = Awaited<ReturnType<typeof realtimeGatewayEvents>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof realtimeGatewayEvents>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getRealtimeGatewayEventsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
