/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { TemplateLibraryControllerFindAllParams } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Browse/search templates with filters
 */
export const templateLibraryControllerFindAll = (
  params?: TemplateLibraryControllerFindAllParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/templates/library`,
    method: 'GET',
    params,
    signal,
  });
};

export const getTemplateLibraryControllerFindAllQueryKey = (
  params?: TemplateLibraryControllerFindAllParams,
) => {
  return [`/api/v1/templates/library`, ...(params ? [params] : [])] as const;
};

export const getTemplateLibraryControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof templateLibraryControllerFindAll>>,
  TError = unknown,
>(
  params?: TemplateLibraryControllerFindAllParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof templateLibraryControllerFindAll>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTemplateLibraryControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof templateLibraryControllerFindAll>>> = ({
    signal,
  }) => templateLibraryControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof templateLibraryControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TemplateLibraryControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof templateLibraryControllerFindAll>>
>;
export type TemplateLibraryControllerFindAllQueryError = unknown;

/**
 * @summary Browse/search templates with filters
 */

export function useTemplateLibraryControllerFindAll<
  TData = Awaited<ReturnType<typeof templateLibraryControllerFindAll>>,
  TError = unknown,
>(
  params?: TemplateLibraryControllerFindAllParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof templateLibraryControllerFindAll>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTemplateLibraryControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get featured/curated templates
 */
export const templateLibraryControllerFindFeatured = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/templates/library/featured`,
    method: 'GET',
    signal,
  });
};

export const getTemplateLibraryControllerFindFeaturedQueryKey = () => {
  return [`/api/v1/templates/library/featured`] as const;
};

export const getTemplateLibraryControllerFindFeaturedQueryOptions = <
  TData = Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTemplateLibraryControllerFindFeaturedQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>
  > = ({ signal }) => templateLibraryControllerFindFeatured(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TemplateLibraryControllerFindFeaturedQueryResult = NonNullable<
  Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>
>;
export type TemplateLibraryControllerFindFeaturedQueryError = unknown;

/**
 * @summary Get featured/curated templates
 */

export function useTemplateLibraryControllerFindFeatured<
  TData = Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof templateLibraryControllerFindFeatured>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTemplateLibraryControllerFindFeaturedQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a single template by ID
 */
export const templateLibraryControllerFindOne = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/templates/library/${id}`,
    method: 'GET',
    signal,
  });
};

export const getTemplateLibraryControllerFindOneQueryKey = (id?: number) => {
  return [`/api/v1/templates/library/${id}`] as const;
};

export const getTemplateLibraryControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof templateLibraryControllerFindOne>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof templateLibraryControllerFindOne>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTemplateLibraryControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof templateLibraryControllerFindOne>>> = ({
    signal,
  }) => templateLibraryControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof templateLibraryControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TemplateLibraryControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof templateLibraryControllerFindOne>>
>;
export type TemplateLibraryControllerFindOneQueryError = void;

/**
 * @summary Get a single template by ID
 */

export function useTemplateLibraryControllerFindOne<
  TData = Awaited<ReturnType<typeof templateLibraryControllerFindOne>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof templateLibraryControllerFindOne>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getTemplateLibraryControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Mark template as used by current user
 */
export const templateLibraryControllerUseTemplate = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/templates/library/${id}/use`,
    method: 'POST',
    signal,
  });
};

export const getTemplateLibraryControllerUseTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof templateLibraryControllerUseTemplate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof templateLibraryControllerUseTemplate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['templateLibraryControllerUseTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof templateLibraryControllerUseTemplate>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return templateLibraryControllerUseTemplate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type TemplateLibraryControllerUseTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof templateLibraryControllerUseTemplate>>
>;

export type TemplateLibraryControllerUseTemplateMutationError = unknown;

/**
 * @summary Mark template as used by current user
 */
export const useTemplateLibraryControllerUseTemplate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof templateLibraryControllerUseTemplate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof templateLibraryControllerUseTemplate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getTemplateLibraryControllerUseTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
