/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ChangePasswordDtoDTO,
  LoginDtoDTO,
  RegisterDtoDTO,
  SendOtpDtoDTO,
  SendPhoneOtpDtoDTO,
  VerifyOtpDtoDTO,
  VerifyPhoneOtpDtoDTO,
} from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Register new user
 */
export const authControllerRegister = (registerDtoDTO: RegisterDtoDTO, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerDtoDTO,
    signal,
  });
};

export const getAuthControllerRegisterMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegister>>,
    TError,
    { data: RegisterDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegister>>,
  TError,
  { data: RegisterDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerRegister'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegister>>,
    { data: RegisterDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegister>>
>;
export type AuthControllerRegisterMutationBody = RegisterDtoDTO;
export type AuthControllerRegisterMutationError = void;

/**
 * @summary Register new user
 */
export const useAuthControllerRegister = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegister>>,
    TError,
    { data: RegisterDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegister>>,
  TError,
  { data: RegisterDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerRegisterMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Login user
 */
export const authControllerLogin = (loginDtoDTO: LoginDtoDTO, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginDtoDTO,
    signal,
  });
};

export const getAuthControllerLoginMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogin>>,
    { data: LoginDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = LoginDtoDTO;
export type AuthControllerLoginMutationError = void;

/**
 * @summary Login user
 */
export const useAuthControllerLogin = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Refresh access token
 */
export const authControllerRefresh = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/auth/refresh`, method: 'POST', signal });
};

export const getAuthControllerRefreshMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerRefresh'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    void
  > = () => {
    return authControllerRefresh();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefresh>>
>;

export type AuthControllerRefreshMutationError = void;

/**
 * @summary Refresh access token
 */
export const useAuthControllerRefresh = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthControllerRefreshMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Logout user
 */
export const authControllerLogout = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/auth/logout`, method: 'POST', signal });
};

export const getAuthControllerLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerLogout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogout>>,
    void
  > = () => {
    return authControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogout>>
>;

export type AuthControllerLogoutMutationError = unknown;

/**
 * @summary Logout user
 */
export const useAuthControllerLogout = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
  const mutationOptions = getAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get current user
 */
export const authControllerGetMe = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/auth/me`, method: 'GET', signal });
};

export const getAuthControllerGetMeQueryKey = () => {
  return [`/api/v1/auth/me`] as const;
};

export const getAuthControllerGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetMe>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMe>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetMe>>> = ({ signal }) =>
    authControllerGetMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetMe>>
>;
export type AuthControllerGetMeQueryError = unknown;

/**
 * @summary Get current user
 */

export function useAuthControllerGetMe<
  TData = Awaited<ReturnType<typeof authControllerGetMe>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMe>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAuthControllerGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Sends a 6-digit OTP to the user's email for password verification. For development, use OTP: 123456
 * @summary Send OTP for password change
 */
export const authControllerSendPasswordChangeOtp = (
  sendOtpDtoDTO: SendOtpDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/password/send-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendOtpDtoDTO,
    signal,
  });
};

export const getAuthControllerSendPasswordChangeOtpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSendPasswordChangeOtp>>,
    TError,
    { data: SendOtpDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSendPasswordChangeOtp>>,
  TError,
  { data: SendOtpDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerSendPasswordChangeOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSendPasswordChangeOtp>>,
    { data: SendOtpDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerSendPasswordChangeOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSendPasswordChangeOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSendPasswordChangeOtp>>
>;
export type AuthControllerSendPasswordChangeOtpMutationBody = SendOtpDtoDTO;
export type AuthControllerSendPasswordChangeOtpMutationError = void;

/**
 * @summary Send OTP for password change
 */
export const useAuthControllerSendPasswordChangeOtp = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSendPasswordChangeOtp>>,
    TError,
    { data: SendOtpDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSendPasswordChangeOtp>>,
  TError,
  { data: SendOtpDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerSendPasswordChangeOtpMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Verifies the OTP and returns a temporary token for password change. Development OTP: 123456
 * @summary Verify OTP and get token
 */
export const authControllerVerifyOtp = (verifyOtpDtoDTO: VerifyOtpDtoDTO, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/password/verify-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verifyOtpDtoDTO,
    signal,
  });
};

export const getAuthControllerVerifyOtpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerifyOtp>>,
    TError,
    { data: VerifyOtpDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerVerifyOtp>>,
  TError,
  { data: VerifyOtpDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerVerifyOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerVerifyOtp>>,
    { data: VerifyOtpDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerVerifyOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerifyOtp>>
>;
export type AuthControllerVerifyOtpMutationBody = VerifyOtpDtoDTO;
export type AuthControllerVerifyOtpMutationError = void;

/**
 * @summary Verify OTP and get token
 */
export const useAuthControllerVerifyOtp = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerifyOtp>>,
    TError,
    { data: VerifyOtpDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerVerifyOtp>>,
  TError,
  { data: VerifyOtpDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerVerifyOtpMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Changes the user password using the OTP verification token
 * @summary Change password with OTP token
 */
export const authControllerChangePassword = (
  changePasswordDtoDTO: ChangePasswordDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/password/change`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: changePasswordDtoDTO,
    signal,
  });
};

export const getAuthControllerChangePasswordMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerChangePassword>>,
    TError,
    { data: ChangePasswordDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerChangePassword>>,
  TError,
  { data: ChangePasswordDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerChangePassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerChangePassword>>,
    { data: ChangePasswordDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerChangePassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerChangePassword>>
>;
export type AuthControllerChangePasswordMutationBody = ChangePasswordDtoDTO;
export type AuthControllerChangePasswordMutationError = void;

/**
 * @summary Change password with OTP token
 */
export const useAuthControllerChangePassword = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerChangePassword>>,
    TError,
    { data: ChangePasswordDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerChangePassword>>,
  TError,
  { data: ChangePasswordDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerChangePasswordMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Sends a 6-digit OTP via SMS. For development, use OTP: 123456
 * @summary Send OTP to phone number
 */
export const authControllerSendPhoneOtp = (
  sendPhoneOtpDtoDTO: SendPhoneOtpDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/phone/send-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendPhoneOtpDtoDTO,
    signal,
  });
};

export const getAuthControllerSendPhoneOtpMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSendPhoneOtp>>,
    TError,
    { data: SendPhoneOtpDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSendPhoneOtp>>,
  TError,
  { data: SendPhoneOtpDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerSendPhoneOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSendPhoneOtp>>,
    { data: SendPhoneOtpDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerSendPhoneOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSendPhoneOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSendPhoneOtp>>
>;
export type AuthControllerSendPhoneOtpMutationBody = SendPhoneOtpDtoDTO;
export type AuthControllerSendPhoneOtpMutationError = unknown;

/**
 * @summary Send OTP to phone number
 */
export const useAuthControllerSendPhoneOtp = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSendPhoneOtp>>,
    TError,
    { data: SendPhoneOtpDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSendPhoneOtp>>,
  TError,
  { data: SendPhoneOtpDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerSendPhoneOtpMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Verifies OTP and returns JWT tokens. Creates a new user if phone is not registered. Dev OTP: 123456
 * @summary Verify phone OTP and get tokens
 */
export const authControllerVerifyPhoneOtp = (
  verifyPhoneOtpDtoDTO: VerifyPhoneOtpDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/auth/phone/verify-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verifyPhoneOtpDtoDTO,
    signal,
  });
};

export const getAuthControllerVerifyPhoneOtpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerifyPhoneOtp>>,
    TError,
    { data: VerifyPhoneOtpDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerVerifyPhoneOtp>>,
  TError,
  { data: VerifyPhoneOtpDtoDTO },
  TContext
> => {
  const mutationKey = ['authControllerVerifyPhoneOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerVerifyPhoneOtp>>,
    { data: VerifyPhoneOtpDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return authControllerVerifyPhoneOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyPhoneOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerifyPhoneOtp>>
>;
export type AuthControllerVerifyPhoneOtpMutationBody = VerifyPhoneOtpDtoDTO;
export type AuthControllerVerifyPhoneOtpMutationError = void;

/**
 * @summary Verify phone OTP and get tokens
 */
export const useAuthControllerVerifyPhoneOtp = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerifyPhoneOtp>>,
    TError,
    { data: VerifyPhoneOtpDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerVerifyPhoneOtp>>,
  TError,
  { data: VerifyPhoneOtpDtoDTO },
  TContext
> => {
  const mutationOptions = getAuthControllerVerifyPhoneOtpMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Initiate Google OAuth flow
 */
export const authControllerGoogleAuth = (signal?: AbortSignal) => {
  return customAxiosInstance<unknown>({ url: `/api/v1/auth/google`, method: 'GET', signal });
};

export const getAuthControllerGoogleAuthQueryKey = () => {
  return [`/api/v1/auth/google`] as const;
};

export const getAuthControllerGoogleAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGoogleAuthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleAuth>>> = ({
    signal,
  }) => authControllerGoogleAuth(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleAuth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGoogleAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleAuth>>
>;
export type AuthControllerGoogleAuthQueryError = void;

/**
 * @summary Initiate Google OAuth flow
 */

export function useAuthControllerGoogleAuth<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAuthControllerGoogleAuthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Google OAuth callback
 */
export const authControllerGoogleAuthCallback = (signal?: AbortSignal) => {
  return customAxiosInstance<unknown>({
    url: `/api/v1/auth/google/callback`,
    method: 'GET',
    signal,
  });
};

export const getAuthControllerGoogleAuthCallbackQueryKey = () => {
  return [`/api/v1/auth/google/callback`] as const;
};

export const getAuthControllerGoogleAuthCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGoogleAuthCallbackQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>> = ({
    signal,
  }) => authControllerGoogleAuthCallback(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGoogleAuthCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>
>;
export type AuthControllerGoogleAuthCallbackQueryError = void;

/**
 * @summary Google OAuth callback
 */

export function useAuthControllerGoogleAuthCallback<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleAuthCallback>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAuthControllerGoogleAuthCallbackQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Exchange OAuth authorization code for tokens
 */
export const authControllerExchangeOAuthCode = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/auth/oauth/exchange`, method: 'POST', signal });
};

export const getAuthControllerExchangeOAuthCodeMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerExchangeOAuthCode>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerExchangeOAuthCode>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerExchangeOAuthCode'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerExchangeOAuthCode>>,
    void
  > = () => {
    return authControllerExchangeOAuthCode();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerExchangeOAuthCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerExchangeOAuthCode>>
>;

export type AuthControllerExchangeOAuthCodeMutationError = void;

/**
 * @summary Exchange OAuth authorization code for tokens
 */
export const useAuthControllerExchangeOAuthCode = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerExchangeOAuthCode>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerExchangeOAuthCode>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthControllerExchangeOAuthCodeMutationOptions(options);

  return useMutation(mutationOptions);
};
