/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AnalyticsControllerGetEngagementParams,
  AnalyticsControllerGetOverviewParams,
  AnalyticsControllerGetPlatformsParams,
} from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get overview statistics
 */
export const analyticsControllerGetOverview = (
  params?: AnalyticsControllerGetOverviewParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/analytics/overview`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAnalyticsControllerGetOverviewQueryKey = (
  params?: AnalyticsControllerGetOverviewParams,
) => {
  return [`/api/v1/analytics/overview`, ...(params ? [params] : [])] as const;
};

export const getAnalyticsControllerGetOverviewQueryOptions = <
  TData = Awaited<ReturnType<typeof analyticsControllerGetOverview>>,
  TError = unknown,
>(
  params?: AnalyticsControllerGetOverviewParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetOverview>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnalyticsControllerGetOverviewQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof analyticsControllerGetOverview>>> = ({
    signal,
  }) => analyticsControllerGetOverview(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetOverview>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AnalyticsControllerGetOverviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof analyticsControllerGetOverview>>
>;
export type AnalyticsControllerGetOverviewQueryError = unknown;

/**
 * @summary Get overview statistics
 */

export function useAnalyticsControllerGetOverview<
  TData = Awaited<ReturnType<typeof analyticsControllerGetOverview>>,
  TError = unknown,
>(
  params?: AnalyticsControllerGetOverviewParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetOverview>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAnalyticsControllerGetOverviewQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get engagement data over time
 */
export const analyticsControllerGetEngagement = (
  params?: AnalyticsControllerGetEngagementParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/analytics/engagement`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAnalyticsControllerGetEngagementQueryKey = (
  params?: AnalyticsControllerGetEngagementParams,
) => {
  return [`/api/v1/analytics/engagement`, ...(params ? [params] : [])] as const;
};

export const getAnalyticsControllerGetEngagementQueryOptions = <
  TData = Awaited<ReturnType<typeof analyticsControllerGetEngagement>>,
  TError = unknown,
>(
  params?: AnalyticsControllerGetEngagementParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetEngagement>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnalyticsControllerGetEngagementQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof analyticsControllerGetEngagement>>> = ({
    signal,
  }) => analyticsControllerGetEngagement(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetEngagement>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AnalyticsControllerGetEngagementQueryResult = NonNullable<
  Awaited<ReturnType<typeof analyticsControllerGetEngagement>>
>;
export type AnalyticsControllerGetEngagementQueryError = unknown;

/**
 * @summary Get engagement data over time
 */

export function useAnalyticsControllerGetEngagement<
  TData = Awaited<ReturnType<typeof analyticsControllerGetEngagement>>,
  TError = unknown,
>(
  params?: AnalyticsControllerGetEngagementParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetEngagement>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAnalyticsControllerGetEngagementQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get platform performance breakdown
 */
export const analyticsControllerGetPlatforms = (
  params?: AnalyticsControllerGetPlatformsParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/analytics/platforms`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAnalyticsControllerGetPlatformsQueryKey = (
  params?: AnalyticsControllerGetPlatformsParams,
) => {
  return [`/api/v1/analytics/platforms`, ...(params ? [params] : [])] as const;
};

export const getAnalyticsControllerGetPlatformsQueryOptions = <
  TData = Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>,
  TError = unknown,
>(
  params?: AnalyticsControllerGetPlatformsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnalyticsControllerGetPlatformsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>> = ({
    signal,
  }) => analyticsControllerGetPlatforms(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AnalyticsControllerGetPlatformsQueryResult = NonNullable<
  Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>
>;
export type AnalyticsControllerGetPlatformsQueryError = unknown;

/**
 * @summary Get platform performance breakdown
 */

export function useAnalyticsControllerGetPlatforms<
  TData = Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>,
  TError = unknown,
>(
  params?: AnalyticsControllerGetPlatformsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof analyticsControllerGetPlatforms>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAnalyticsControllerGetPlatformsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get top performing content
 */
export const analyticsControllerGetTopContent = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/analytics/top-content`, method: 'GET', signal });
};

export const getAnalyticsControllerGetTopContentQueryKey = () => {
  return [`/api/v1/analytics/top-content`] as const;
};

export const getAnalyticsControllerGetTopContentQueryOptions = <
  TData = Awaited<ReturnType<typeof analyticsControllerGetTopContent>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetTopContent>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAnalyticsControllerGetTopContentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof analyticsControllerGetTopContent>>> = ({
    signal,
  }) => analyticsControllerGetTopContent(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetTopContent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AnalyticsControllerGetTopContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof analyticsControllerGetTopContent>>
>;
export type AnalyticsControllerGetTopContentQueryError = unknown;

/**
 * @summary Get top performing content
 */

export function useAnalyticsControllerGetTopContent<
  TData = Awaited<ReturnType<typeof analyticsControllerGetTopContent>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof analyticsControllerGetTopContent>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAnalyticsControllerGetTopContentQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
