/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { InsightsControllerGetUserInsightsParams } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary List all insight templates (admin)
 */
export const insightsControllerGetTemplates = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/insights/templates`, method: 'GET', signal });
};

export const getInsightsControllerGetTemplatesQueryKey = () => {
  return [`/api/v1/insights/templates`] as const;
};

export const getInsightsControllerGetTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof insightsControllerGetTemplates>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof insightsControllerGetTemplates>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInsightsControllerGetTemplatesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof insightsControllerGetTemplates>>> = ({
    signal,
  }) => insightsControllerGetTemplates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof insightsControllerGetTemplates>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type InsightsControllerGetTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof insightsControllerGetTemplates>>
>;
export type InsightsControllerGetTemplatesQueryError = unknown;

/**
 * @summary List all insight templates (admin)
 */

export function useInsightsControllerGetTemplates<
  TData = Awaited<ReturnType<typeof insightsControllerGetTemplates>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof insightsControllerGetTemplates>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getInsightsControllerGetTemplatesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get user insights (personalized, rendered)
 */
export const insightsControllerGetUserInsights = (
  params: InsightsControllerGetUserInsightsParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({ url: `/api/v1/insights`, method: 'GET', params, signal });
};

export const getInsightsControllerGetUserInsightsQueryKey = (
  params?: InsightsControllerGetUserInsightsParams,
) => {
  return [`/api/v1/insights`, ...(params ? [params] : [])] as const;
};

export const getInsightsControllerGetUserInsightsQueryOptions = <
  TData = Awaited<ReturnType<typeof insightsControllerGetUserInsights>>,
  TError = unknown,
>(
  params: InsightsControllerGetUserInsightsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof insightsControllerGetUserInsights>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInsightsControllerGetUserInsightsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof insightsControllerGetUserInsights>>> = ({
    signal,
  }) => insightsControllerGetUserInsights(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof insightsControllerGetUserInsights>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type InsightsControllerGetUserInsightsQueryResult = NonNullable<
  Awaited<ReturnType<typeof insightsControllerGetUserInsights>>
>;
export type InsightsControllerGetUserInsightsQueryError = unknown;

/**
 * @summary Get user insights (personalized, rendered)
 */

export function useInsightsControllerGetUserInsights<
  TData = Awaited<ReturnType<typeof insightsControllerGetUserInsights>>,
  TError = unknown,
>(
  params: InsightsControllerGetUserInsightsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof insightsControllerGetUserInsights>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getInsightsControllerGetUserInsightsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Mark an insight as clicked
 */
export const insightsControllerMarkClicked = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/insights/${id}/click`, method: 'PATCH' });
};

export const getInsightsControllerMarkClickedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof insightsControllerMarkClicked>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof insightsControllerMarkClicked>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['insightsControllerMarkClicked'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof insightsControllerMarkClicked>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return insightsControllerMarkClicked(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type InsightsControllerMarkClickedMutationResult = NonNullable<
  Awaited<ReturnType<typeof insightsControllerMarkClicked>>
>;

export type InsightsControllerMarkClickedMutationError = unknown;

/**
 * @summary Mark an insight as clicked
 */
export const useInsightsControllerMarkClicked = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof insightsControllerMarkClicked>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof insightsControllerMarkClicked>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getInsightsControllerMarkClickedMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Dismiss an insight
 */
export const insightsControllerMarkDismissed = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/insights/${id}/dismiss`, method: 'PATCH' });
};

export const getInsightsControllerMarkDismissedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof insightsControllerMarkDismissed>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof insightsControllerMarkDismissed>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['insightsControllerMarkDismissed'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof insightsControllerMarkDismissed>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return insightsControllerMarkDismissed(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type InsightsControllerMarkDismissedMutationResult = NonNullable<
  Awaited<ReturnType<typeof insightsControllerMarkDismissed>>
>;

export type InsightsControllerMarkDismissedMutationError = unknown;

/**
 * @summary Dismiss an insight
 */
export const useInsightsControllerMarkDismissed = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof insightsControllerMarkDismissed>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof insightsControllerMarkDismissed>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getInsightsControllerMarkDismissedMutationOptions(options);

  return useMutation(mutationOptions);
};
