/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { MediaAssetsControllerFindAllParams } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Record a media asset after CDN upload
 */
export const mediaAssetsControllerUpload = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/media/upload`, method: 'POST', signal });
};

export const getMediaAssetsControllerUploadMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerUpload>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mediaAssetsControllerUpload>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['mediaAssetsControllerUpload'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mediaAssetsControllerUpload>>,
    void
  > = () => {
    return mediaAssetsControllerUpload();
  };

  return { mutationFn, ...mutationOptions };
};

export type MediaAssetsControllerUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof mediaAssetsControllerUpload>>
>;

export type MediaAssetsControllerUploadMutationError = unknown;

/**
 * @summary Record a media asset after CDN upload
 */
export const useMediaAssetsControllerUpload = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerUpload>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof mediaAssetsControllerUpload>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getMediaAssetsControllerUploadMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary List media assets with filters
 */
export const mediaAssetsControllerFindAll = (
  params?: MediaAssetsControllerFindAllParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({ url: `/api/v1/media`, method: 'GET', params, signal });
};

export const getMediaAssetsControllerFindAllQueryKey = (
  params?: MediaAssetsControllerFindAllParams,
) => {
  return [`/api/v1/media`, ...(params ? [params] : [])] as const;
};

export const getMediaAssetsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>,
  TError = unknown,
>(
  params?: MediaAssetsControllerFindAllParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMediaAssetsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>> = ({
    signal,
  }) => mediaAssetsControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type MediaAssetsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>
>;
export type MediaAssetsControllerFindAllQueryError = unknown;

/**
 * @summary List media assets with filters
 */

export function useMediaAssetsControllerFindAll<
  TData = Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>,
  TError = unknown,
>(
  params?: MediaAssetsControllerFindAllParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof mediaAssetsControllerFindAll>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMediaAssetsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get storage usage stats
 */
export const mediaAssetsControllerGetStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/media/stats`, method: 'GET', signal });
};

export const getMediaAssetsControllerGetStatsQueryKey = () => {
  return [`/api/v1/media/stats`] as const;
};

export const getMediaAssetsControllerGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMediaAssetsControllerGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>> = ({
    signal,
  }) => mediaAssetsControllerGetStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type MediaAssetsControllerGetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>
>;
export type MediaAssetsControllerGetStatsQueryError = unknown;

/**
 * @summary Get storage usage stats
 */

export function useMediaAssetsControllerGetStats<
  TData = Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof mediaAssetsControllerGetStats>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMediaAssetsControllerGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a single media asset by ID
 */
export const mediaAssetsControllerFindOne = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/media/${id}`, method: 'GET', signal });
};

export const getMediaAssetsControllerFindOneQueryKey = (id?: number) => {
  return [`/api/v1/media/${id}`] as const;
};

export const getMediaAssetsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMediaAssetsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>> = ({
    signal,
  }) => mediaAssetsControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type MediaAssetsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>
>;
export type MediaAssetsControllerFindOneQueryError = void;

/**
 * @summary Get a single media asset by ID
 */

export function useMediaAssetsControllerFindOne<
  TData = Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>,
  TError = void,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof mediaAssetsControllerFindOne>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMediaAssetsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete a media asset
 */
export const mediaAssetsControllerRemove = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/media/${id}`, method: 'DELETE' });
};

export const getMediaAssetsControllerRemoveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mediaAssetsControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['mediaAssetsControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mediaAssetsControllerRemove>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return mediaAssetsControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type MediaAssetsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof mediaAssetsControllerRemove>>
>;

export type MediaAssetsControllerRemoveMutationError = void;

/**
 * @summary Delete a media asset
 */
export const useMediaAssetsControllerRemove = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mediaAssetsControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof mediaAssetsControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getMediaAssetsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
