/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { DashboardControllerGetRecentParams } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get comprehensive dashboard statistics
 */
export const dashboardControllerGetStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/dashboard/stats`, method: 'GET', signal });
};

export const getDashboardControllerGetStatsQueryKey = () => {
  return [`/api/v1/dashboard/stats`] as const;
};

export const getDashboardControllerGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof dashboardControllerGetStats>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDashboardControllerGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dashboardControllerGetStats>>> = ({
    signal,
  }) => dashboardControllerGetStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardControllerGetStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DashboardControllerGetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardControllerGetStats>>
>;
export type DashboardControllerGetStatsQueryError = unknown;

/**
 * @summary Get comprehensive dashboard statistics
 */

export function useDashboardControllerGetStats<
  TData = Awaited<ReturnType<typeof dashboardControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof dashboardControllerGetStats>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getDashboardControllerGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get recent content for dashboard
 */
export const dashboardControllerGetRecent = (
  params?: DashboardControllerGetRecentParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/dashboard/recent`,
    method: 'GET',
    params,
    signal,
  });
};

export const getDashboardControllerGetRecentQueryKey = (
  params?: DashboardControllerGetRecentParams,
) => {
  return [`/api/v1/dashboard/recent`, ...(params ? [params] : [])] as const;
};

export const getDashboardControllerGetRecentQueryOptions = <
  TData = Awaited<ReturnType<typeof dashboardControllerGetRecent>>,
  TError = unknown,
>(
  params?: DashboardControllerGetRecentParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof dashboardControllerGetRecent>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDashboardControllerGetRecentQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dashboardControllerGetRecent>>> = ({
    signal,
  }) => dashboardControllerGetRecent(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashboardControllerGetRecent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DashboardControllerGetRecentQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashboardControllerGetRecent>>
>;
export type DashboardControllerGetRecentQueryError = unknown;

/**
 * @summary Get recent content for dashboard
 */

export function useDashboardControllerGetRecent<
  TData = Awaited<ReturnType<typeof dashboardControllerGetRecent>>,
  TError = unknown,
>(
  params?: DashboardControllerGetRecentParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof dashboardControllerGetRecent>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getDashboardControllerGetRecentQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
