/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Receive incoming engagement (webhook from n8n)
 */
export const engagementControllerIncoming = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/engagement/incoming`, method: 'POST', signal });
};

export const getEngagementControllerIncomingMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerIncoming>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof engagementControllerIncoming>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['engagementControllerIncoming'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof engagementControllerIncoming>>,
    void
  > = () => {
    return engagementControllerIncoming();
  };

  return { mutationFn, ...mutationOptions };
};

export type EngagementControllerIncomingMutationResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerIncoming>>
>;

export type EngagementControllerIncomingMutationError = unknown;

/**
 * @summary Receive incoming engagement (webhook from n8n)
 */
export const useEngagementControllerIncoming = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerIncoming>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof engagementControllerIncoming>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getEngagementControllerIncomingMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary List engagement interactions (inbox)
 */
export const engagementControllerFindAll = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/engagement`, method: 'GET', signal });
};

export const getEngagementControllerFindAllQueryKey = () => {
  return [`/api/v1/engagement`] as const;
};

export const getEngagementControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof engagementControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof engagementControllerFindAll>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEngagementControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof engagementControllerFindAll>>> = ({
    signal,
  }) => engagementControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof engagementControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EngagementControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerFindAll>>
>;
export type EngagementControllerFindAllQueryError = unknown;

/**
 * @summary List engagement interactions (inbox)
 */

export function useEngagementControllerFindAll<
  TData = Awaited<ReturnType<typeof engagementControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof engagementControllerFindAll>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getEngagementControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Manually respond to an interaction
 */
export const engagementControllerRespond = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/engagement/${id}/respond`, method: 'PATCH' });
};

export const getEngagementControllerRespondMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerRespond>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof engagementControllerRespond>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['engagementControllerRespond'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof engagementControllerRespond>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return engagementControllerRespond(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type EngagementControllerRespondMutationResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerRespond>>
>;

export type EngagementControllerRespondMutationError = unknown;

/**
 * @summary Manually respond to an interaction
 */
export const useEngagementControllerRespond = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerRespond>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof engagementControllerRespond>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getEngagementControllerRespondMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Skip/dismiss an interaction
 */
export const engagementControllerSkip = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/engagement/${id}/skip`, method: 'PATCH' });
};

export const getEngagementControllerSkipMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerSkip>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof engagementControllerSkip>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['engagementControllerSkip'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof engagementControllerSkip>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return engagementControllerSkip(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type EngagementControllerSkipMutationResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerSkip>>
>;

export type EngagementControllerSkipMutationError = unknown;

/**
 * @summary Skip/dismiss an interaction
 */
export const useEngagementControllerSkip = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerSkip>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof engagementControllerSkip>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getEngagementControllerSkipMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Create a suggested outbound comment (requires user approval before posting)
 */
export const engagementControllerSuggestComment = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/engagement/suggest-comment`,
    method: 'POST',
    signal,
  });
};

export const getEngagementControllerSuggestCommentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerSuggestComment>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof engagementControllerSuggestComment>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['engagementControllerSuggestComment'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof engagementControllerSuggestComment>>,
    void
  > = () => {
    return engagementControllerSuggestComment();
  };

  return { mutationFn, ...mutationOptions };
};

export type EngagementControllerSuggestCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerSuggestComment>>
>;

export type EngagementControllerSuggestCommentMutationError = unknown;

/**
 * @summary Create a suggested outbound comment (requires user approval before posting)
 */
export const useEngagementControllerSuggestComment = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerSuggestComment>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof engagementControllerSuggestComment>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getEngagementControllerSuggestCommentMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Approve a suggested comment for posting
 */
export const engagementControllerApproveSuggested = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/engagement/${id}/approve`, method: 'PATCH' });
};

export const getEngagementControllerApproveSuggestedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerApproveSuggested>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof engagementControllerApproveSuggested>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['engagementControllerApproveSuggested'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof engagementControllerApproveSuggested>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return engagementControllerApproveSuggested(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type EngagementControllerApproveSuggestedMutationResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerApproveSuggested>>
>;

export type EngagementControllerApproveSuggestedMutationError = unknown;

/**
 * @summary Approve a suggested comment for posting
 */
export const useEngagementControllerApproveSuggested = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof engagementControllerApproveSuggested>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof engagementControllerApproveSuggested>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getEngagementControllerApproveSuggestedMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get engagement statistics
 */
export const engagementControllerGetStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/engagement/stats`, method: 'GET', signal });
};

export const getEngagementControllerGetStatsQueryKey = () => {
  return [`/api/v1/engagement/stats`] as const;
};

export const getEngagementControllerGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof engagementControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof engagementControllerGetStats>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getEngagementControllerGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof engagementControllerGetStats>>> = ({
    signal,
  }) => engagementControllerGetStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof engagementControllerGetStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type EngagementControllerGetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof engagementControllerGetStats>>
>;
export type EngagementControllerGetStatsQueryError = unknown;

/**
 * @summary Get engagement statistics
 */

export function useEngagementControllerGetStats<
  TData = Awaited<ReturnType<typeof engagementControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof engagementControllerGetStats>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getEngagementControllerGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
