/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Callback from n8n after content is published
 */
export const n8nControllerContentPublished = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/webhooks/n8n/content-published`,
    method: 'POST',
    signal,
  });
};

export const getN8nControllerContentPublishedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof n8nControllerContentPublished>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof n8nControllerContentPublished>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['n8nControllerContentPublished'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof n8nControllerContentPublished>>,
    void
  > = () => {
    return n8nControllerContentPublished();
  };

  return { mutationFn, ...mutationOptions };
};

export type N8nControllerContentPublishedMutationResult = NonNullable<
  Awaited<ReturnType<typeof n8nControllerContentPublished>>
>;

export type N8nControllerContentPublishedMutationError = unknown;

/**
 * @summary Callback from n8n after content is published
 */
export const useN8nControllerContentPublished = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof n8nControllerContentPublished>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof n8nControllerContentPublished>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getN8nControllerContentPublishedMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Callback from n8n when new review is detected
 */
export const n8nControllerReviewReceived = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/webhooks/n8n/review-received`,
    method: 'POST',
    signal,
  });
};

export const getN8nControllerReviewReceivedMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof n8nControllerReviewReceived>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof n8nControllerReviewReceived>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['n8nControllerReviewReceived'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof n8nControllerReviewReceived>>,
    void
  > = () => {
    return n8nControllerReviewReceived();
  };

  return { mutationFn, ...mutationOptions };
};

export type N8nControllerReviewReceivedMutationResult = NonNullable<
  Awaited<ReturnType<typeof n8nControllerReviewReceived>>
>;

export type N8nControllerReviewReceivedMutationError = unknown;

/**
 * @summary Callback from n8n when new review is detected
 */
export const useN8nControllerReviewReceived = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof n8nControllerReviewReceived>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof n8nControllerReviewReceived>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getN8nControllerReviewReceivedMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Callback from n8n with trending topic data
 */
export const n8nControllerTrendingUpdate = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/webhooks/n8n/trending-update`,
    method: 'POST',
    signal,
  });
};

export const getN8nControllerTrendingUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof n8nControllerTrendingUpdate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof n8nControllerTrendingUpdate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['n8nControllerTrendingUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof n8nControllerTrendingUpdate>>,
    void
  > = () => {
    return n8nControllerTrendingUpdate();
  };

  return { mutationFn, ...mutationOptions };
};

export type N8nControllerTrendingUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof n8nControllerTrendingUpdate>>
>;

export type N8nControllerTrendingUpdateMutationError = unknown;

/**
 * @summary Callback from n8n with trending topic data
 */
export const useN8nControllerTrendingUpdate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof n8nControllerTrendingUpdate>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof n8nControllerTrendingUpdate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getN8nControllerTrendingUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
