/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Manually trigger AI models synchronization (requires auth)
 */
export const schedulerControllerTriggerModelSync = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/scheduler/sync-models`,
    method: 'POST',
    signal,
  });
};

export const getSchedulerControllerTriggerModelSyncMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schedulerControllerTriggerModelSync>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof schedulerControllerTriggerModelSync>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['schedulerControllerTriggerModelSync'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof schedulerControllerTriggerModelSync>>,
    void
  > = () => {
    return schedulerControllerTriggerModelSync();
  };

  return { mutationFn, ...mutationOptions };
};

export type SchedulerControllerTriggerModelSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof schedulerControllerTriggerModelSync>>
>;

export type SchedulerControllerTriggerModelSyncMutationError = unknown;

/**
 * @summary Manually trigger AI models synchronization (requires auth)
 */
export const useSchedulerControllerTriggerModelSync = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof schedulerControllerTriggerModelSync>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof schedulerControllerTriggerModelSync>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSchedulerControllerTriggerModelSyncMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get AI models sync statistics (requires auth)
 */
export const schedulerControllerGetSyncStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/scheduler/sync-stats`, method: 'GET', signal });
};

export const getSchedulerControllerGetSyncStatsQueryKey = () => {
  return [`/api/v1/scheduler/sync-stats`] as const;
};

export const getSchedulerControllerGetSyncStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSchedulerControllerGetSyncStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>> = ({
    signal,
  }) => schedulerControllerGetSyncStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SchedulerControllerGetSyncStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>
>;
export type SchedulerControllerGetSyncStatsQueryError = unknown;

/**
 * @summary Get AI models sync statistics (requires auth)
 */

export function useSchedulerControllerGetSyncStats<
  TData = Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof schedulerControllerGetSyncStats>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSchedulerControllerGetSyncStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
