/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AIControllerGetAllModelsParams,
  AIControllerGetAnalyticsParams,
  AIControllerGetSuggestionsParams,
  FeedbackDtoDTO,
  GenerateCaptionRequestDTO,
  GenerateHashtagsRequestDTO,
  GenerateHooksRequestDTO,
  GenerateIdeasRequestDTO,
  TaskRequestDtoDTO,
} from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Generate content with intelligent model selection
 */
export const aIControllerGenerateWithTask = (
  taskRequestDtoDTO: TaskRequestDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/task`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: taskRequestDtoDTO,
    signal,
  });
};

export const getAIControllerGenerateWithTaskMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
    TError,
    { data: TaskRequestDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
  TError,
  { data: TaskRequestDtoDTO },
  TContext
> => {
  const mutationKey = ['aIControllerGenerateWithTask'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
    { data: TaskRequestDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerGenerateWithTask(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateWithTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateWithTask>>
>;
export type AIControllerGenerateWithTaskMutationBody = TaskRequestDtoDTO;
export type AIControllerGenerateWithTaskMutationError = unknown;

/**
 * @summary Generate content with intelligent model selection
 */
export const useAIControllerGenerateWithTask = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
    TError,
    { data: TaskRequestDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
  TError,
  { data: TaskRequestDtoDTO },
  TContext
> => {
  const mutationOptions = getAIControllerGenerateWithTaskMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get best model for a task without executing
 */
export const aIControllerSelectModel = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/select-model`, method: 'POST', signal });
};

export const getAIControllerSelectModelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerSelectModel>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerSelectModel>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerSelectModel'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerSelectModel>>,
    void
  > = () => {
    return aIControllerSelectModel();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerSelectModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerSelectModel>>
>;

export type AIControllerSelectModelMutationError = unknown;

/**
 * @summary Get best model for a task without executing
 */
export const useAIControllerSelectModel = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerSelectModel>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerSelectModel>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerSelectModelMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get available models for capability
 */
export const aIControllerGetModelsByCapability = (capability: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/models/${capability}`,
    method: 'GET',
    signal,
  });
};

export const getAIControllerGetModelsByCapabilityQueryKey = (capability?: string) => {
  return [`/api/v1/ai/models/${capability}`] as const;
};

export const getAIControllerGetModelsByCapabilityQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>,
  TError = unknown,
>(
  capability: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAIControllerGetModelsByCapabilityQueryKey(capability);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>> = ({
    signal,
  }) => aIControllerGetModelsByCapability(capability, signal);

  return { queryKey, queryFn, enabled: !!capability, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetModelsByCapabilityQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>
>;
export type AIControllerGetModelsByCapabilityQueryError = unknown;

/**
 * @summary Get available models for capability
 */

export function useAIControllerGetModelsByCapability<
  TData = Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>,
  TError = unknown,
>(
  capability: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetModelsByCapability>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetModelsByCapabilityQueryOptions(capability, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get all available AI models (paginated)
 */
export const aIControllerGetAllModels = (
  params: AIControllerGetAllModelsParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/models`, method: 'GET', params, signal });
};

export const getAIControllerGetAllModelsQueryKey = (params?: AIControllerGetAllModelsParams) => {
  return [`/api/v1/ai/models`, ...(params ? [params] : [])] as const;
};

export const getAIControllerGetAllModelsQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetAllModels>>,
  TError = unknown,
>(
  params: AIControllerGetAllModelsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetAllModels>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetAllModelsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetAllModels>>> = ({
    signal,
  }) => aIControllerGetAllModels(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetAllModels>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetAllModelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetAllModels>>
>;
export type AIControllerGetAllModelsQueryError = unknown;

/**
 * @summary Get all available AI models (paginated)
 */

export function useAIControllerGetAllModels<
  TData = Awaited<ReturnType<typeof aIControllerGetAllModels>>,
  TError = unknown,
>(
  params: AIControllerGetAllModelsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetAllModels>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetAllModelsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Submit feedback on AI output
 */
export const aIControllerRecordFeedback = (
  feedbackDtoDTO: FeedbackDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/feedback`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: feedbackDtoDTO,
    signal,
  });
};

export const getAIControllerRecordFeedbackMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
    TError,
    { data: FeedbackDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
  TError,
  { data: FeedbackDtoDTO },
  TContext
> => {
  const mutationKey = ['aIControllerRecordFeedback'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
    { data: FeedbackDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerRecordFeedback(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerRecordFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerRecordFeedback>>
>;
export type AIControllerRecordFeedbackMutationBody = FeedbackDtoDTO;
export type AIControllerRecordFeedbackMutationError = unknown;

/**
 * @summary Submit feedback on AI output
 */
export const useAIControllerRecordFeedback = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
    TError,
    { data: FeedbackDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
  TError,
  { data: FeedbackDtoDTO },
  TContext
> => {
  const mutationOptions = getAIControllerRecordFeedbackMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get user preferred models for category
 */
export const aIControllerGetUserPreferences = (category: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/preferences/${category}`,
    method: 'GET',
    signal,
  });
};

export const getAIControllerGetUserPreferencesQueryKey = (category?: string) => {
  return [`/api/v1/ai/preferences/${category}`] as const;
};

export const getAIControllerGetUserPreferencesQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
  TError = unknown,
>(
  category: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetUserPreferencesQueryKey(category);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetUserPreferences>>> = ({
    signal,
  }) => aIControllerGetUserPreferences(category, signal);

  return { queryKey, queryFn, enabled: !!category, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetUserPreferencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetUserPreferences>>
>;
export type AIControllerGetUserPreferencesQueryError = unknown;

/**
 * @summary Get user preferred models for category
 */

export function useAIControllerGetUserPreferences<
  TData = Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
  TError = unknown,
>(
  category: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetUserPreferencesQueryOptions(category, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get model statistics
 */
export const aIControllerGetModelStats = (
  modelId: number,
  category: string,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/stats/${modelId}/${category}`,
    method: 'GET',
    signal,
  });
};

export const getAIControllerGetModelStatsQueryKey = (modelId?: number, category?: string) => {
  return [`/api/v1/ai/stats/${modelId}/${category}`] as const;
};

export const getAIControllerGetModelStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetModelStats>>,
  TError = unknown,
>(
  modelId: number,
  category: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetModelStats>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAIControllerGetModelStatsQueryKey(modelId, category);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetModelStats>>> = ({
    signal,
  }) => aIControllerGetModelStats(modelId, category, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(modelId && category),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetModelStats>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type AIControllerGetModelStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetModelStats>>
>;
export type AIControllerGetModelStatsQueryError = unknown;

/**
 * @summary Get model statistics
 */

export function useAIControllerGetModelStats<
  TData = Awaited<ReturnType<typeof aIControllerGetModelStats>>,
  TError = unknown,
>(
  modelId: number,
  category: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetModelStats>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetModelStatsQueryOptions(modelId, category, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Generate 5 content ideas/storylines
 */
export const aIControllerGenerateIdeas = (
  generateIdeasRequestDTO: GenerateIdeasRequestDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/ideas`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateIdeasRequestDTO,
    signal,
  });
};

export const getAIControllerGenerateIdeasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
    TError,
    { data: GenerateIdeasRequestDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
  TError,
  { data: GenerateIdeasRequestDTO },
  TContext
> => {
  const mutationKey = ['aIControllerGenerateIdeas'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
    { data: GenerateIdeasRequestDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerGenerateIdeas(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateIdeasMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateIdeas>>
>;
export type AIControllerGenerateIdeasMutationBody = GenerateIdeasRequestDTO;
export type AIControllerGenerateIdeasMutationError = unknown;

/**
 * @summary Generate 5 content ideas/storylines
 */
export const useAIControllerGenerateIdeas = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
    TError,
    { data: GenerateIdeasRequestDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
  TError,
  { data: GenerateIdeasRequestDTO },
  TContext
> => {
  const mutationOptions = getAIControllerGenerateIdeasMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate social media caption
 */
export const aIControllerGenerateCaption = (
  generateCaptionRequestDTO: GenerateCaptionRequestDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/caption`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateCaptionRequestDTO,
    signal,
  });
};

export const getAIControllerGenerateCaptionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
    TError,
    { data: GenerateCaptionRequestDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
  TError,
  { data: GenerateCaptionRequestDTO },
  TContext
> => {
  const mutationKey = ['aIControllerGenerateCaption'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
    { data: GenerateCaptionRequestDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerGenerateCaption(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateCaptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateCaption>>
>;
export type AIControllerGenerateCaptionMutationBody = GenerateCaptionRequestDTO;
export type AIControllerGenerateCaptionMutationError = unknown;

/**
 * @summary Generate social media caption
 */
export const useAIControllerGenerateCaption = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
    TError,
    { data: GenerateCaptionRequestDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
  TError,
  { data: GenerateCaptionRequestDTO },
  TContext
> => {
  const mutationOptions = getAIControllerGenerateCaptionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate attention-grabbing hooks
 */
export const aIControllerGenerateHooks = (
  generateHooksRequestDTO: GenerateHooksRequestDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/hooks`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateHooksRequestDTO,
    signal,
  });
};

export const getAIControllerGenerateHooksMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
    TError,
    { data: GenerateHooksRequestDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
  TError,
  { data: GenerateHooksRequestDTO },
  TContext
> => {
  const mutationKey = ['aIControllerGenerateHooks'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
    { data: GenerateHooksRequestDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerGenerateHooks(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateHooksMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateHooks>>
>;
export type AIControllerGenerateHooksMutationBody = GenerateHooksRequestDTO;
export type AIControllerGenerateHooksMutationError = unknown;

/**
 * @summary Generate attention-grabbing hooks
 */
export const useAIControllerGenerateHooks = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
    TError,
    { data: GenerateHooksRequestDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
  TError,
  { data: GenerateHooksRequestDTO },
  TContext
> => {
  const mutationOptions = getAIControllerGenerateHooksMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate SEO hashtags
 */
export const aIControllerGenerateHashtags = (
  generateHashtagsRequestDTO: GenerateHashtagsRequestDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/hashtags`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generateHashtagsRequestDTO,
    signal,
  });
};

export const getAIControllerGenerateHashtagsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
    TError,
    { data: GenerateHashtagsRequestDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
  TError,
  { data: GenerateHashtagsRequestDTO },
  TContext
> => {
  const mutationKey = ['aIControllerGenerateHashtags'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
    { data: GenerateHashtagsRequestDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerGenerateHashtags(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateHashtagsMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateHashtags>>
>;
export type AIControllerGenerateHashtagsMutationBody = GenerateHashtagsRequestDTO;
export type AIControllerGenerateHashtagsMutationError = unknown;

/**
 * @summary Generate SEO hashtags
 */
export const useAIControllerGenerateHashtags = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
    TError,
    { data: GenerateHashtagsRequestDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
  TError,
  { data: GenerateHashtagsRequestDTO },
  TContext
> => {
  const mutationOptions = getAIControllerGenerateHashtagsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get AI suggestions for timing and trends
 */
export const aIControllerGetSuggestions = (
  params: AIControllerGetSuggestionsParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/suggestions`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAIControllerGetSuggestionsQueryKey = (
  params?: AIControllerGetSuggestionsParams,
) => {
  return [`/api/v1/ai/suggestions`, ...(params ? [params] : [])] as const;
};

export const getAIControllerGetSuggestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetSuggestions>>,
  TError = unknown,
>(
  params: AIControllerGetSuggestionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetSuggestions>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetSuggestionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetSuggestions>>> = ({
    signal,
  }) => aIControllerGetSuggestions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetSuggestions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetSuggestionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetSuggestions>>
>;
export type AIControllerGetSuggestionsQueryError = unknown;

/**
 * @summary Get AI suggestions for timing and trends
 */

export function useAIControllerGetSuggestions<
  TData = Awaited<ReturnType<typeof aIControllerGetSuggestions>>,
  TError = unknown,
>(
  params: AIControllerGetSuggestionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetSuggestions>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetSuggestionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Stream AI caption generation in real-time
 */
export const aIControllerStreamCaption = (
  generateCaptionRequestDTO: GenerateCaptionRequestDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/stream/caption`,
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
    signal,
  });
};

export const getAIControllerStreamCaptionQueryKey = (
  generateCaptionRequestDTO?: GenerateCaptionRequestDTO,
) => {
  return [`/api/v1/ai/stream/caption`, generateCaptionRequestDTO] as const;
};

export const getAIControllerStreamCaptionQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerStreamCaption>>,
  TError = unknown,
>(
  generateCaptionRequestDTO: GenerateCaptionRequestDTO,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerStreamCaption>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAIControllerStreamCaptionQueryKey(generateCaptionRequestDTO);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerStreamCaption>>> = ({
    signal,
  }) => aIControllerStreamCaption(generateCaptionRequestDTO, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerStreamCaption>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerStreamCaptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerStreamCaption>>
>;
export type AIControllerStreamCaptionQueryError = unknown;

/**
 * @summary Stream AI caption generation in real-time
 */

export function useAIControllerStreamCaption<
  TData = Awaited<ReturnType<typeof aIControllerStreamCaption>>,
  TError = unknown,
>(
  generateCaptionRequestDTO: GenerateCaptionRequestDTO,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerStreamCaption>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerStreamCaptionQueryOptions(generateCaptionRequestDTO, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get AI usage analytics for user
 */
export const aIControllerGetAnalytics = (
  params: AIControllerGetAnalyticsParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/analytics`, method: 'GET', params, signal });
};

export const getAIControllerGetAnalyticsQueryKey = (params?: AIControllerGetAnalyticsParams) => {
  return [`/api/v1/ai/analytics`, ...(params ? [params] : [])] as const;
};

export const getAIControllerGetAnalyticsQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetAnalytics>>,
  TError = unknown,
>(
  params: AIControllerGetAnalyticsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetAnalytics>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetAnalyticsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetAnalytics>>> = ({
    signal,
  }) => aIControllerGetAnalytics(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetAnalytics>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetAnalyticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetAnalytics>>
>;
export type AIControllerGetAnalyticsQueryError = unknown;

/**
 * @summary Get AI usage analytics for user
 */

export function useAIControllerGetAnalytics<
  TData = Awaited<ReturnType<typeof aIControllerGetAnalytics>>,
  TError = unknown,
>(
  params: AIControllerGetAnalyticsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetAnalytics>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetAnalyticsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Generate an image prompt for AI image generation
 */
export const aIControllerGenerateImagePrompt = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/image-prompt`,
    method: 'POST',
    signal,
  });
};

export const getAIControllerGenerateImagePromptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateImagePrompt>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateImagePrompt>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerGenerateImagePrompt'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateImagePrompt>>,
    void
  > = () => {
    return aIControllerGenerateImagePrompt();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateImagePromptMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateImagePrompt>>
>;

export type AIControllerGenerateImagePromptMutationError = unknown;

/**
 * @summary Generate an image prompt for AI image generation
 */
export const useAIControllerGenerateImagePrompt = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateImagePrompt>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateImagePrompt>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerGenerateImagePromptMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate AI response for a review, comment, or message
 */
export const aIControllerGenerateEngagementResponse = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/engagement-response`,
    method: 'POST',
    signal,
  });
};

export const getAIControllerGenerateEngagementResponseMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateEngagementResponse>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateEngagementResponse>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerGenerateEngagementResponse'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateEngagementResponse>>,
    void
  > = () => {
    return aIControllerGenerateEngagementResponse();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateEngagementResponseMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateEngagementResponse>>
>;

export type AIControllerGenerateEngagementResponseMutationError = unknown;

/**
 * @summary Generate AI response for a review, comment, or message
 */
export const useAIControllerGenerateEngagementResponse = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateEngagementResponse>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateEngagementResponse>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerGenerateEngagementResponseMutationOptions(options);

  return useMutation(mutationOptions);
};
