/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get user referral code and link
 */
export const referralsControllerGetMyCode = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/referrals/my-code`, method: 'GET', signal });
};

export const getReferralsControllerGetMyCodeQueryKey = () => {
  return [`/api/v1/referrals/my-code`] as const;
};

export const getReferralsControllerGetMyCodeQueryOptions = <
  TData = Awaited<ReturnType<typeof referralsControllerGetMyCode>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof referralsControllerGetMyCode>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReferralsControllerGetMyCodeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof referralsControllerGetMyCode>>> = ({
    signal,
  }) => referralsControllerGetMyCode(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof referralsControllerGetMyCode>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ReferralsControllerGetMyCodeQueryResult = NonNullable<
  Awaited<ReturnType<typeof referralsControllerGetMyCode>>
>;
export type ReferralsControllerGetMyCodeQueryError = unknown;

/**
 * @summary Get user referral code and link
 */

export function useReferralsControllerGetMyCode<
  TData = Awaited<ReturnType<typeof referralsControllerGetMyCode>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof referralsControllerGetMyCode>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getReferralsControllerGetMyCodeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get referral statistics
 */
export const referralsControllerGetStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/referrals/stats`, method: 'GET', signal });
};

export const getReferralsControllerGetStatsQueryKey = () => {
  return [`/api/v1/referrals/stats`] as const;
};

export const getReferralsControllerGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof referralsControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof referralsControllerGetStats>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getReferralsControllerGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof referralsControllerGetStats>>> = ({
    signal,
  }) => referralsControllerGetStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof referralsControllerGetStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ReferralsControllerGetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof referralsControllerGetStats>>
>;
export type ReferralsControllerGetStatsQueryError = unknown;

/**
 * @summary Get referral statistics
 */

export function useReferralsControllerGetStats<
  TData = Awaited<ReturnType<typeof referralsControllerGetStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof referralsControllerGetStats>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getReferralsControllerGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Apply a referral code during signup
 */
export const referralsControllerApply = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/referrals/apply`, method: 'POST', signal });
};

export const getReferralsControllerApplyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof referralsControllerApply>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof referralsControllerApply>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['referralsControllerApply'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof referralsControllerApply>>,
    void
  > = () => {
    return referralsControllerApply();
  };

  return { mutationFn, ...mutationOptions };
};

export type ReferralsControllerApplyMutationResult = NonNullable<
  Awaited<ReturnType<typeof referralsControllerApply>>
>;

export type ReferralsControllerApplyMutationError = unknown;

/**
 * @summary Apply a referral code during signup
 */
export const useReferralsControllerApply = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof referralsControllerApply>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof referralsControllerApply>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getReferralsControllerApplyMutationOptions(options);

  return useMutation(mutationOptions);
};
