/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary List all achievement definitions
 */
export const gamificationControllerGetDefinitions = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/gamification/definitions`,
    method: 'GET',
    signal,
  });
};

export const getGamificationControllerGetDefinitionsQueryKey = () => {
  return [`/api/v1/gamification/definitions`] as const;
};

export const getGamificationControllerGetDefinitionsQueryOptions = <
  TData = Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGamificationControllerGetDefinitionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>
  > = ({ signal }) => gamificationControllerGetDefinitions(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GamificationControllerGetDefinitionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>
>;
export type GamificationControllerGetDefinitionsQueryError = unknown;

/**
 * @summary List all achievement definitions
 */

export function useGamificationControllerGetDefinitions<
  TData = Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof gamificationControllerGetDefinitions>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGamificationControllerGetDefinitionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get user achievements (unlocked + in-progress)
 */
export const gamificationControllerGetUserAchievements = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/gamification/achievements`,
    method: 'GET',
    signal,
  });
};

export const getGamificationControllerGetUserAchievementsQueryKey = () => {
  return [`/api/v1/gamification/achievements`] as const;
};

export const getGamificationControllerGetUserAchievementsQueryOptions = <
  TData = Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGamificationControllerGetUserAchievementsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>
  > = ({ signal }) => gamificationControllerGetUserAchievements(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GamificationControllerGetUserAchievementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>
>;
export type GamificationControllerGetUserAchievementsQueryError = unknown;

/**
 * @summary Get user achievements (unlocked + in-progress)
 */

export function useGamificationControllerGetUserAchievements<
  TData = Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof gamificationControllerGetUserAchievements>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGamificationControllerGetUserAchievementsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
