/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get top-performing content suggestions for re-posting
 */
export const contentRecyclingControllerGetSuggestions = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/content/recycling/suggestions`,
    method: 'GET',
    signal,
  });
};

export const getContentRecyclingControllerGetSuggestionsQueryKey = () => {
  return [`/api/v1/content/recycling/suggestions`] as const;
};

export const getContentRecyclingControllerGetSuggestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentRecyclingControllerGetSuggestionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>
  > = ({ signal }) => contentRecyclingControllerGetSuggestions(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContentRecyclingControllerGetSuggestionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>
>;
export type ContentRecyclingControllerGetSuggestionsQueryError = unknown;

/**
 * @summary Get top-performing content suggestions for re-posting
 */

export function useContentRecyclingControllerGetSuggestions<
  TData = Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof contentRecyclingControllerGetSuggestions>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContentRecyclingControllerGetSuggestionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
