import { execSync, spawn } from 'child_process';
import type { ChildProcess } from 'child_process';
import * as net from 'net';

const ROOT = process.cwd();
const API_PORT = 8000;
const API_HEALTH_URL = `http://localhost:${API_PORT}/api/v1/docs-json`;

const c = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  magenta: '\x1b[35m',
};

function log(msg: string, color = c.reset) {
  console.log(`${color}${msg}${c.reset}`);
}

function run(label: string, cmd: string, exitOnFail = true): boolean {
  log(`\n  >> ${label}`, c.blue);
  log(`     $ ${cmd}`, c.yellow);
  try {
    execSync(cmd, { stdio: 'inherit', cwd: ROOT });
    log(`     done!`, c.green);
    return true;
  } catch {
    log(`     FAILED: ${label}`, c.red);
    if (exitOnFail) process.exit(1);
    return false;
  }
}

// Check if a port is accepting connections
function isPortOpen(port: number): Promise<boolean> {
  return new Promise(resolve => {
    const socket = new net.Socket();
    socket.setTimeout(1000);
    socket
      .connect(port, 'localhost', () => {
        socket.destroy();
        resolve(true);
      })
      .on('error', () => {
        socket.destroy();
        resolve(false);
      })
      .on('timeout', () => {
        socket.destroy();
        resolve(false);
      });
  });
}

// Wait until API port is open, polling every second
async function waitForApi(port: number, timeoutSecs = 60): Promise<boolean> {
  log(`\n  Waiting for API to start on port ${port}...`, c.yellow);
  for (let i = 0; i < timeoutSecs; i++) {
    const open = await isPortOpen(port);
    if (open) {
      log(`  API is up on port ${port}!`, c.green);
      return true;
    }
    process.stdout.write(`\r${c.yellow}  Waiting... ${i + 1}s${c.reset}`);
    await new Promise(r => setTimeout(r, 1000));
  }
  console.log('');
  log(`  Timed out waiting for API after ${timeoutSecs}s`, c.red);
  return false;
}

// Kill process and all its children
function killProcess(proc: ChildProcess) {
  try {
    if (proc.pid) {
      // On Windows, kill the entire process tree
      execSync(`taskkill /PID ${proc.pid} /T /F`, { stdio: 'ignore' });
      log(`\n  API process killed (PID ${proc.pid})`, c.green);
    }
  } catch {
    // Already dead
  }
}

async function main() {
  const start = Date.now();

  console.log('');
  log('  ================================================', c.magenta);
  log('   BusinessPro — Full Project Setup', c.magenta);
  log('  ================================================', c.magenta);
  console.log('');

  // ── 1. Install all workspace dependencies ───────────
  log('\n  [1/4] Installing all dependencies...', c.cyan);
  run('bun install (root + all workspaces)', 'bun install');

  // ── 2. Build packages in dependency order ───────────
  log('\n  [2/4] Building workspace packages...', c.cyan);
  // shared-utils first (no deps on other packages)
  run('Build @businesspro/shared-utils', 'bun run --filter @businesspro/shared-utils build', false);
  // ai second (used by API - needs to emit to dist/ so NestJS can import it)
  run('Build @businesspro/ai', 'bun run build:ai');
  // auth-ui last (used by Next.js via transpilePackages - build for type safety)
  run('Build @businesspro/auth-ui', 'bun run build:auth-ui', false);
  // api-client is generated by Orval, no manual build needed

  // ── 3. Start API + Generate Orval UI clients ────────
  log('\n  [3/4] Starting API to generate UI clients...', c.cyan);
  log(`  Starting API server in background...`, c.yellow);

  // Check if API already running
  const alreadyRunning = await isPortOpen(API_PORT);
  let apiProcess: ChildProcess | null = null;

  if (alreadyRunning) {
    log(`  API already running on port ${API_PORT}`, c.green);
  } else {
    // Spawn API as background process
    apiProcess = spawn('bun', ['run', 'api:dev'], {
      cwd: ROOT,
      stdio: 'ignore',
      detached: false,
      shell: true,
    });

    log(`  API process started (PID: ${apiProcess.pid})`, c.cyan);

    // Wait up to 60 seconds for API to be ready
    const ready = await waitForApi(API_PORT, 60);
    if (!ready) {
      log('\n  Could not start API. Skipping UI client generation.', c.red);
      if (apiProcess) killProcess(apiProcess);
    }
  }

  // Extra 2s buffer for NestJS to finish registering all routes/swagger
  log(`  Waiting 2s for Swagger to initialize...`, c.yellow);
  await new Promise(r => setTimeout(r, 2000));

  // Generate UI clients
  log(`\n  Generating UI clients from ${API_HEALTH_URL}`, c.cyan);
  run('Orval — generate UI clients', 'bun run generate:ui-client', false);

  // Kill the API we started (user will start it themselves)
  if (apiProcess) {
    killProcess(apiProcess);
  }

  // ── 4. Setup Java + Android SDK ─────────────────────
  log('\n  [4/4] Setting up Java & Android SDK...', c.cyan);
  run(
    'Configure JAVA_HOME + ANDROID_HOME',
    'powershell -ExecutionPolicy Bypass -File ./packages/scripts/setup-java-env.ps1',
    false,
  );

  // ── Done ─────────────────────────────────────────────
  const secs = ((Date.now() - start) / 1000).toFixed(1);
  console.log('');
  log('  ================================================', c.green);
  log(`   Setup complete in ${secs}s!`, c.green);
  log('  ================================================', c.green);
  console.log('');
  log('  Next steps:', c.cyan);
  log('    1. Reopen terminal  — for env vars to take effect', c.yellow);
  log('    2. bun run dev      — start all dev servers', c.yellow);
  log('    3. bun run dev:web  — frontend only', c.yellow);
  log('    4. bun run dev:api  — API only', c.yellow);
  log('    5. bun run mobile:run:android  — Android emulator', c.yellow);
  console.log('');
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
