/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get all platform connections
 */
export const platformsControllerGetAllConnections = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/platforms`, method: 'GET', signal });
};

export const getPlatformsControllerGetAllConnectionsQueryKey = () => {
  return [`/api/v1/platforms`] as const;
};

export const getPlatformsControllerGetAllConnectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof platformsControllerGetAllConnections>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetAllConnections>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlatformsControllerGetAllConnectionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof platformsControllerGetAllConnections>>
  > = ({ signal }) => platformsControllerGetAllConnections(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetAllConnections>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformsControllerGetAllConnectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof platformsControllerGetAllConnections>>
>;
export type PlatformsControllerGetAllConnectionsQueryError = unknown;

/**
 * @summary Get all platform connections
 */

export function usePlatformsControllerGetAllConnections<
  TData = Awaited<ReturnType<typeof platformsControllerGetAllConnections>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetAllConnections>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPlatformsControllerGetAllConnectionsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get list of connected platforms
 */
export const platformsControllerGetConnectedPlatforms = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/platforms/connected`, method: 'GET', signal });
};

export const getPlatformsControllerGetConnectedPlatformsQueryKey = () => {
  return [`/api/v1/platforms/connected`] as const;
};

export const getPlatformsControllerGetConnectedPlatformsQueryOptions = <
  TData = Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlatformsControllerGetConnectedPlatformsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>
  > = ({ signal }) => platformsControllerGetConnectedPlatforms(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformsControllerGetConnectedPlatformsQueryResult = NonNullable<
  Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>
>;
export type PlatformsControllerGetConnectedPlatformsQueryError = unknown;

/**
 * @summary Get list of connected platforms
 */

export function usePlatformsControllerGetConnectedPlatforms<
  TData = Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetConnectedPlatforms>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPlatformsControllerGetConnectedPlatformsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get connection status for a platform
 */
export const platformsControllerGetStatus = (platform: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/platforms/${platform}/status`,
    method: 'GET',
    signal,
  });
};

export const getPlatformsControllerGetStatusQueryKey = (platform?: string) => {
  return [`/api/v1/platforms/${platform}/status`] as const;
};

export const getPlatformsControllerGetStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof platformsControllerGetStatus>>,
  TError = unknown,
>(
  platform: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof platformsControllerGetStatus>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlatformsControllerGetStatusQueryKey(platform);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof platformsControllerGetStatus>>> = ({
    signal,
  }) => platformsControllerGetStatus(platform, signal);

  return { queryKey, queryFn, enabled: !!platform, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof platformsControllerGetStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformsControllerGetStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof platformsControllerGetStatus>>
>;
export type PlatformsControllerGetStatusQueryError = unknown;

/**
 * @summary Get connection status for a platform
 */

export function usePlatformsControllerGetStatus<
  TData = Awaited<ReturnType<typeof platformsControllerGetStatus>>,
  TError = unknown,
>(
  platform: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof platformsControllerGetStatus>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPlatformsControllerGetStatusQueryOptions(platform, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Connect a social media platform
 */
export const platformsControllerConnect = (platform: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/platforms/${platform}/connect`,
    method: 'POST',
    signal,
  });
};

export const getPlatformsControllerConnectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformsControllerConnect>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformsControllerConnect>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationKey = ['platformsControllerConnect'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformsControllerConnect>>,
    { platform: string }
  > = props => {
    const { platform } = props ?? {};

    return platformsControllerConnect(platform);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformsControllerConnectMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformsControllerConnect>>
>;

export type PlatformsControllerConnectMutationError = unknown;

/**
 * @summary Connect a social media platform
 */
export const usePlatformsControllerConnect = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformsControllerConnect>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformsControllerConnect>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationOptions = getPlatformsControllerConnectMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Disconnect a social media platform
 */
export const platformsControllerDisconnect = (platform: string) => {
  return customAxiosInstance<void>({
    url: `/api/v1/platforms/${platform}/disconnect`,
    method: 'DELETE',
  });
};

export const getPlatformsControllerDisconnectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformsControllerDisconnect>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformsControllerDisconnect>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationKey = ['platformsControllerDisconnect'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformsControllerDisconnect>>,
    { platform: string }
  > = props => {
    const { platform } = props ?? {};

    return platformsControllerDisconnect(platform);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformsControllerDisconnectMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformsControllerDisconnect>>
>;

export type PlatformsControllerDisconnectMutationError = unknown;

/**
 * @summary Disconnect a social media platform
 */
export const usePlatformsControllerDisconnect = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformsControllerDisconnect>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformsControllerDisconnect>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationOptions = getPlatformsControllerDisconnectMutationOptions(options);

  return useMutation(mutationOptions);
};
