/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { UpdateAppSettingDtoDTO } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get all app settings (admin only)
 */
export const appSettingsControllerGetAll = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/settings/app`, method: 'GET', signal });
};

export const getAppSettingsControllerGetAllQueryKey = () => {
  return [`/api/v1/settings/app`] as const;
};

export const getAppSettingsControllerGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof appSettingsControllerGetAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appSettingsControllerGetAll>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppSettingsControllerGetAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appSettingsControllerGetAll>>> = ({
    signal,
  }) => appSettingsControllerGetAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appSettingsControllerGetAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppSettingsControllerGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof appSettingsControllerGetAll>>
>;
export type AppSettingsControllerGetAllQueryError = unknown;

/**
 * @summary Get all app settings (admin only)
 */

export function useAppSettingsControllerGetAll<
  TData = Awaited<ReturnType<typeof appSettingsControllerGetAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appSettingsControllerGetAll>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppSettingsControllerGetAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an app setting by key (admin only)
 */
export const appSettingsControllerUpdate = (
  key: string,
  updateAppSettingDtoDTO: UpdateAppSettingDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/settings/app/${key}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAppSettingDtoDTO,
  });
};

export const getAppSettingsControllerUpdateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof appSettingsControllerUpdate>>,
    TError,
    { key: string; data: UpdateAppSettingDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof appSettingsControllerUpdate>>,
  TError,
  { key: string; data: UpdateAppSettingDtoDTO },
  TContext
> => {
  const mutationKey = ['appSettingsControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof appSettingsControllerUpdate>>,
    { key: string; data: UpdateAppSettingDtoDTO }
  > = props => {
    const { key, data } = props ?? {};

    return appSettingsControllerUpdate(key, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AppSettingsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof appSettingsControllerUpdate>>
>;
export type AppSettingsControllerUpdateMutationBody = UpdateAppSettingDtoDTO;
export type AppSettingsControllerUpdateMutationError = void;

/**
 * @summary Update an app setting by key (admin only)
 */
export const useAppSettingsControllerUpdate = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof appSettingsControllerUpdate>>,
    TError,
    { key: string; data: UpdateAppSettingDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof appSettingsControllerUpdate>>,
  TError,
  { key: string; data: UpdateAppSettingDtoDTO },
  TContext
> => {
  const mutationOptions = getAppSettingsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
