/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary List connected platforms for current user
 */
export const platformIntegrationControllerFindAll = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/platform-integration`, method: 'GET', signal });
};

export const getPlatformIntegrationControllerFindAllQueryKey = () => {
  return [`/api/v1/platform-integration`] as const;
};

export const getPlatformIntegrationControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPlatformIntegrationControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>
  > = ({ signal }) => platformIntegrationControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformIntegrationControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>
>;
export type PlatformIntegrationControllerFindAllQueryError = unknown;

/**
 * @summary List connected platforms for current user
 */

export function usePlatformIntegrationControllerFindAll<
  TData = Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerFindAll>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPlatformIntegrationControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Connect a social media platform
 */
export const platformIntegrationControllerConnect = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/platform-integration/connect`,
    method: 'POST',
    signal,
  });
};

export const getPlatformIntegrationControllerConnectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerConnect>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformIntegrationControllerConnect>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['platformIntegrationControllerConnect'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformIntegrationControllerConnect>>,
    void
  > = () => {
    return platformIntegrationControllerConnect();
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformIntegrationControllerConnectMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformIntegrationControllerConnect>>
>;

export type PlatformIntegrationControllerConnectMutationError = unknown;

/**
 * @summary Connect a social media platform
 */
export const usePlatformIntegrationControllerConnect = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerConnect>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformIntegrationControllerConnect>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPlatformIntegrationControllerConnectMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Disconnect a platform
 */
export const platformIntegrationControllerDisconnect = (platform: string) => {
  return customAxiosInstance<void>({
    url: `/api/v1/platform-integration/${platform}`,
    method: 'DELETE',
  });
};

export const getPlatformIntegrationControllerDisconnectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerDisconnect>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformIntegrationControllerDisconnect>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationKey = ['platformIntegrationControllerDisconnect'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformIntegrationControllerDisconnect>>,
    { platform: string }
  > = props => {
    const { platform } = props ?? {};

    return platformIntegrationControllerDisconnect(platform);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformIntegrationControllerDisconnectMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformIntegrationControllerDisconnect>>
>;

export type PlatformIntegrationControllerDisconnectMutationError = unknown;

/**
 * @summary Disconnect a platform
 */
export const usePlatformIntegrationControllerDisconnect = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformIntegrationControllerDisconnect>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformIntegrationControllerDisconnect>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationOptions = getPlatformIntegrationControllerDisconnectMutationOptions(options);

  return useMutation(mutationOptions);
};
