/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GeneratePlanDtoDTO, UpdatePlanItemDtoDTO } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary AI-generate a weekly or monthly content plan
 */
export const contentPlansControllerGenerate = (
  generatePlanDtoDTO: GeneratePlanDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/content-plans/generate`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: generatePlanDtoDTO,
    signal,
  });
};

export const getContentPlansControllerGenerateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerGenerate>>,
    TError,
    { data: GeneratePlanDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentPlansControllerGenerate>>,
  TError,
  { data: GeneratePlanDtoDTO },
  TContext
> => {
  const mutationKey = ['contentPlansControllerGenerate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentPlansControllerGenerate>>,
    { data: GeneratePlanDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return contentPlansControllerGenerate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentPlansControllerGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentPlansControllerGenerate>>
>;
export type ContentPlansControllerGenerateMutationBody = GeneratePlanDtoDTO;
export type ContentPlansControllerGenerateMutationError = unknown;

/**
 * @summary AI-generate a weekly or monthly content plan
 */
export const useContentPlansControllerGenerate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerGenerate>>,
    TError,
    { data: GeneratePlanDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contentPlansControllerGenerate>>,
  TError,
  { data: GeneratePlanDtoDTO },
  TContext
> => {
  const mutationOptions = getContentPlansControllerGenerateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary List user content plans
 */
export const contentPlansControllerFindAll = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/content-plans`, method: 'GET', signal });
};

export const getContentPlansControllerFindAllQueryKey = () => {
  return [`/api/v1/content-plans`] as const;
};

export const getContentPlansControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof contentPlansControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof contentPlansControllerFindAll>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentPlansControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentPlansControllerFindAll>>> = ({
    signal,
  }) => contentPlansControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentPlansControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContentPlansControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentPlansControllerFindAll>>
>;
export type ContentPlansControllerFindAllQueryError = unknown;

/**
 * @summary List user content plans
 */

export function useContentPlansControllerFindAll<
  TData = Awaited<ReturnType<typeof contentPlansControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof contentPlansControllerFindAll>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContentPlansControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a content plan with items
 */
export const contentPlansControllerFindOne = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/content-plans/${id}`, method: 'GET', signal });
};

export const getContentPlansControllerFindOneQueryKey = (id?: number) => {
  return [`/api/v1/content-plans/${id}`] as const;
};

export const getContentPlansControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof contentPlansControllerFindOne>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contentPlansControllerFindOne>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentPlansControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentPlansControllerFindOne>>> = ({
    signal,
  }) => contentPlansControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentPlansControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContentPlansControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentPlansControllerFindOne>>
>;
export type ContentPlansControllerFindOneQueryError = unknown;

/**
 * @summary Get a content plan with items
 */

export function useContentPlansControllerFindOne<
  TData = Awaited<ReturnType<typeof contentPlansControllerFindOne>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contentPlansControllerFindOne>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContentPlansControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Cancel a content plan
 */
export const contentPlansControllerCancel = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/content-plans/${id}`, method: 'DELETE' });
};

export const getContentPlansControllerCancelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerCancel>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentPlansControllerCancel>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['contentPlansControllerCancel'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentPlansControllerCancel>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return contentPlansControllerCancel(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentPlansControllerCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentPlansControllerCancel>>
>;

export type ContentPlansControllerCancelMutationError = unknown;

/**
 * @summary Cancel a content plan
 */
export const useContentPlansControllerCancel = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerCancel>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contentPlansControllerCancel>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getContentPlansControllerCancelMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Update a plan item (approve/reject/edit)
 */
export const contentPlansControllerUpdateItem = (
  planId: number,
  itemId: number,
  updatePlanItemDtoDTO: UpdatePlanItemDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/content-plans/${planId}/items/${itemId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updatePlanItemDtoDTO,
  });
};

export const getContentPlansControllerUpdateItemMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerUpdateItem>>,
    TError,
    { planId: number; itemId: number; data: UpdatePlanItemDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentPlansControllerUpdateItem>>,
  TError,
  { planId: number; itemId: number; data: UpdatePlanItemDtoDTO },
  TContext
> => {
  const mutationKey = ['contentPlansControllerUpdateItem'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentPlansControllerUpdateItem>>,
    { planId: number; itemId: number; data: UpdatePlanItemDtoDTO }
  > = props => {
    const { planId, itemId, data } = props ?? {};

    return contentPlansControllerUpdateItem(planId, itemId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentPlansControllerUpdateItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentPlansControllerUpdateItem>>
>;
export type ContentPlansControllerUpdateItemMutationBody = UpdatePlanItemDtoDTO;
export type ContentPlansControllerUpdateItemMutationError = unknown;

/**
 * @summary Update a plan item (approve/reject/edit)
 */
export const useContentPlansControllerUpdateItem = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerUpdateItem>>,
    TError,
    { planId: number; itemId: number; data: UpdatePlanItemDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contentPlansControllerUpdateItem>>,
  TError,
  { planId: number; itemId: number; data: UpdatePlanItemDtoDTO },
  TContext
> => {
  const mutationOptions = getContentPlansControllerUpdateItemMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Approve entire plan, activate scheduling
 */
export const contentPlansControllerApproveAll = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/content-plans/${id}/approve-all`,
    method: 'POST',
    signal,
  });
};

export const getContentPlansControllerApproveAllMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerApproveAll>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentPlansControllerApproveAll>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['contentPlansControllerApproveAll'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentPlansControllerApproveAll>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return contentPlansControllerApproveAll(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentPlansControllerApproveAllMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentPlansControllerApproveAll>>
>;

export type ContentPlansControllerApproveAllMutationError = unknown;

/**
 * @summary Approve entire plan, activate scheduling
 */
export const useContentPlansControllerApproveAll = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentPlansControllerApproveAll>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contentPlansControllerApproveAll>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getContentPlansControllerApproveAllMutationOptions(options);

  return useMutation(mutationOptions);
};
