/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { FestivalsControllerUpcomingParams } from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary List all active festivals
 */
export const festivalsControllerFindAll = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/festivals`, method: 'GET', signal });
};

export const getFestivalsControllerFindAllQueryKey = () => {
  return [`/api/v1/festivals`] as const;
};

export const getFestivalsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof festivalsControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof festivalsControllerFindAll>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFestivalsControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof festivalsControllerFindAll>>> = ({
    signal,
  }) => festivalsControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof festivalsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FestivalsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof festivalsControllerFindAll>>
>;
export type FestivalsControllerFindAllQueryError = unknown;

/**
 * @summary List all active festivals
 */

export function useFestivalsControllerFindAll<
  TData = Awaited<ReturnType<typeof festivalsControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof festivalsControllerFindAll>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFestivalsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get upcoming festivals
 */
export const festivalsControllerUpcoming = (
  params: FestivalsControllerUpcomingParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/festivals/upcoming`,
    method: 'GET',
    params,
    signal,
  });
};

export const getFestivalsControllerUpcomingQueryKey = (
  params?: FestivalsControllerUpcomingParams,
) => {
  return [`/api/v1/festivals/upcoming`, ...(params ? [params] : [])] as const;
};

export const getFestivalsControllerUpcomingQueryOptions = <
  TData = Awaited<ReturnType<typeof festivalsControllerUpcoming>>,
  TError = unknown,
>(
  params: FestivalsControllerUpcomingParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof festivalsControllerUpcoming>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFestivalsControllerUpcomingQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof festivalsControllerUpcoming>>> = ({
    signal,
  }) => festivalsControllerUpcoming(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof festivalsControllerUpcoming>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FestivalsControllerUpcomingQueryResult = NonNullable<
  Awaited<ReturnType<typeof festivalsControllerUpcoming>>
>;
export type FestivalsControllerUpcomingQueryError = unknown;

/**
 * @summary Get upcoming festivals
 */

export function useFestivalsControllerUpcoming<
  TData = Awaited<ReturnType<typeof festivalsControllerUpcoming>>,
  TError = unknown,
>(
  params: FestivalsControllerUpcomingParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof festivalsControllerUpcoming>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFestivalsControllerUpcomingQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get a festival by ID
 */
export const festivalsControllerFindOne = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/festivals/${id}`, method: 'GET', signal });
};

export const getFestivalsControllerFindOneQueryKey = (id?: number) => {
  return [`/api/v1/festivals/${id}`] as const;
};

export const getFestivalsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof festivalsControllerFindOne>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof festivalsControllerFindOne>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFestivalsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof festivalsControllerFindOne>>> = ({
    signal,
  }) => festivalsControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof festivalsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FestivalsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof festivalsControllerFindOne>>
>;
export type FestivalsControllerFindOneQueryError = unknown;

/**
 * @summary Get a festival by ID
 */

export function useFestivalsControllerFindOne<
  TData = Awaited<ReturnType<typeof festivalsControllerFindOne>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof festivalsControllerFindOne>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFestivalsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
