/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ChangePasswordDtoDTO,
  CompleteOnboardingDtoDTO,
  UpdateAdvancedSettingsDtoDTO,
  UpdateAiSettingsDtoDTO,
  UpdateAnalyticsSettingsDtoDTO,
  UpdateBusinessProfileDtoDTO,
  UpdateNotificationsDtoDTO,
  UpdatePreferencesDtoDTO,
  UpdatePrivacySettingsDtoDTO,
  UpdateSchedulingSettingsDtoDTO,
} from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get user profile
 */
export const usersControllerGetProfile = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/profile`, method: 'GET', signal });
};

export const getUsersControllerGetProfileQueryKey = () => {
  return [`/api/v1/users/profile`] as const;
};

export const getUsersControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetProfile>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetProfile>>> = ({
    signal,
  }) => usersControllerGetProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetProfile>>
>;
export type UsersControllerGetProfileQueryError = unknown;

/**
 * @summary Get user profile
 */

export function useUsersControllerGetProfile<
  TData = Awaited<ReturnType<typeof usersControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetProfile>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update user profile
 */
export const usersControllerUpdateProfile = () => {
  return customAxiosInstance<void>({ url: `/api/v1/users/profile`, method: 'PATCH' });
};

export const getUsersControllerUpdateProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerUpdateProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    void
  > = () => {
    return usersControllerUpdateProfile();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>
>;

export type UsersControllerUpdateProfileMutationError = unknown;

/**
 * @summary Update user profile
 */
export const useUsersControllerUpdateProfile = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * OAuth users must provide business information after signup
 * @summary Complete onboarding for OAuth users
 */
export const usersControllerCompleteOnboarding = (
  completeOnboardingDtoDTO: CompleteOnboardingDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/onboarding/complete`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: completeOnboardingDtoDTO,
    signal,
  });
};

export const getUsersControllerCompleteOnboardingMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerCompleteOnboarding>>,
    TError,
    { data: CompleteOnboardingDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerCompleteOnboarding>>,
  TError,
  { data: CompleteOnboardingDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerCompleteOnboarding'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerCompleteOnboarding>>,
    { data: CompleteOnboardingDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerCompleteOnboarding(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerCompleteOnboardingMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerCompleteOnboarding>>
>;
export type UsersControllerCompleteOnboardingMutationBody = CompleteOnboardingDtoDTO;
export type UsersControllerCompleteOnboardingMutationError = unknown;

/**
 * @summary Complete onboarding for OAuth users
 */
export const useUsersControllerCompleteOnboarding = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerCompleteOnboarding>>,
    TError,
    { data: CompleteOnboardingDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerCompleteOnboarding>>,
  TError,
  { data: CompleteOnboardingDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerCompleteOnboardingMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Update business profile
 */
export const usersControllerUpdateBusinessProfile = (
  updateBusinessProfileDtoDTO: UpdateBusinessProfileDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/business-profile`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateBusinessProfileDtoDTO,
  });
};

export const getUsersControllerUpdateBusinessProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateBusinessProfile>>,
    TError,
    { data: UpdateBusinessProfileDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateBusinessProfile>>,
  TError,
  { data: UpdateBusinessProfileDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateBusinessProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateBusinessProfile>>,
    { data: UpdateBusinessProfileDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdateBusinessProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateBusinessProfile>>
>;
export type UsersControllerUpdateBusinessProfileMutationBody = UpdateBusinessProfileDtoDTO;
export type UsersControllerUpdateBusinessProfileMutationError = unknown;

/**
 * @summary Update business profile
 */
export const useUsersControllerUpdateBusinessProfile = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateBusinessProfile>>,
    TError,
    { data: UpdateBusinessProfileDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateBusinessProfile>>,
  TError,
  { data: UpdateBusinessProfileDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get user preferences
 */
export const usersControllerGetPreferences = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/preferences`, method: 'GET', signal });
};

export const getUsersControllerGetPreferencesQueryKey = () => {
  return [`/api/v1/users/preferences`] as const;
};

export const getUsersControllerGetPreferencesQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetPreferences>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetPreferences>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetPreferencesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetPreferences>>> = ({
    signal,
  }) => usersControllerGetPreferences(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPreferences>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetPreferencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetPreferences>>
>;
export type UsersControllerGetPreferencesQueryError = unknown;

/**
 * @summary Get user preferences
 */

export function useUsersControllerGetPreferences<
  TData = Awaited<ReturnType<typeof usersControllerGetPreferences>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetPreferences>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetPreferencesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update user preferences
 */
export const usersControllerUpdatePreferences = (
  updatePreferencesDtoDTO: UpdatePreferencesDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/preferences`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updatePreferencesDtoDTO,
  });
};

export const getUsersControllerUpdatePreferencesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdatePreferences>>,
    TError,
    { data: UpdatePreferencesDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdatePreferences>>,
  TError,
  { data: UpdatePreferencesDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdatePreferences'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdatePreferences>>,
    { data: UpdatePreferencesDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdatePreferences(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdatePreferencesMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdatePreferences>>
>;
export type UsersControllerUpdatePreferencesMutationBody = UpdatePreferencesDtoDTO;
export type UsersControllerUpdatePreferencesMutationError = unknown;

/**
 * @summary Update user preferences
 */
export const useUsersControllerUpdatePreferences = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdatePreferences>>,
    TError,
    { data: UpdatePreferencesDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdatePreferences>>,
  TError,
  { data: UpdatePreferencesDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdatePreferencesMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get notification settings
 */
export const usersControllerGetNotifications = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/notifications`, method: 'GET', signal });
};

export const getUsersControllerGetNotificationsQueryKey = () => {
  return [`/api/v1/users/notifications`] as const;
};

export const getUsersControllerGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetNotifications>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetNotifications>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetNotificationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetNotifications>>> = ({
    signal,
  }) => usersControllerGetNotifications(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetNotifications>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetNotificationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetNotifications>>
>;
export type UsersControllerGetNotificationsQueryError = unknown;

/**
 * @summary Get notification settings
 */

export function useUsersControllerGetNotifications<
  TData = Awaited<ReturnType<typeof usersControllerGetNotifications>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetNotifications>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetNotificationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update notification settings
 */
export const usersControllerUpdateNotifications = (
  updateNotificationsDtoDTO: UpdateNotificationsDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/notifications`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateNotificationsDtoDTO,
  });
};

export const getUsersControllerUpdateNotificationsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateNotifications>>,
    TError,
    { data: UpdateNotificationsDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateNotifications>>,
  TError,
  { data: UpdateNotificationsDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateNotifications'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateNotifications>>,
    { data: UpdateNotificationsDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdateNotifications(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateNotificationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateNotifications>>
>;
export type UsersControllerUpdateNotificationsMutationBody = UpdateNotificationsDtoDTO;
export type UsersControllerUpdateNotificationsMutationError = unknown;

/**
 * @summary Update notification settings
 */
export const useUsersControllerUpdateNotifications = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateNotifications>>,
    TError,
    { data: UpdateNotificationsDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateNotifications>>,
  TError,
  { data: UpdateNotificationsDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateNotificationsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Change password
 */
export const usersControllerChangePassword = (
  changePasswordDtoDTO: ChangePasswordDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/password`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: changePasswordDtoDTO,
    signal,
  });
};

export const getUsersControllerChangePasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerChangePassword>>,
    TError,
    { data: ChangePasswordDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerChangePassword>>,
  TError,
  { data: ChangePasswordDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerChangePassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerChangePassword>>,
    { data: ChangePasswordDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerChangePassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerChangePassword>>
>;
export type UsersControllerChangePasswordMutationBody = ChangePasswordDtoDTO;
export type UsersControllerChangePasswordMutationError = unknown;

/**
 * @summary Change password
 */
export const useUsersControllerChangePassword = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerChangePassword>>,
    TError,
    { data: ChangePasswordDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerChangePassword>>,
  TError,
  { data: ChangePasswordDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerChangePasswordMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Upload profile avatar
 */
export const usersControllerUploadAvatar = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/avatar`, method: 'POST', signal });
};

export const getUsersControllerUploadAvatarMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUploadAvatar>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUploadAvatar>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerUploadAvatar'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUploadAvatar>>,
    void
  > = () => {
    return usersControllerUploadAvatar();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUploadAvatarMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUploadAvatar>>
>;

export type UsersControllerUploadAvatarMutationError = unknown;

/**
 * @summary Upload profile avatar
 */
export const useUsersControllerUploadAvatar = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUploadAvatar>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUploadAvatar>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerUploadAvatarMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Enable two-factor authentication
 */
export const usersControllerEnable2FA = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/2fa/enable`, method: 'POST', signal });
};

export const getUsersControllerEnable2FAMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerEnable2FA>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerEnable2FA>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerEnable2FA'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerEnable2FA>>,
    void
  > = () => {
    return usersControllerEnable2FA();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerEnable2FAMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerEnable2FA>>
>;

export type UsersControllerEnable2FAMutationError = unknown;

/**
 * @summary Enable two-factor authentication
 */
export const useUsersControllerEnable2FA = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerEnable2FA>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerEnable2FA>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerEnable2FAMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Disable two-factor authentication
 */
export const usersControllerDisable2FA = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/2fa/disable`, method: 'POST', signal });
};

export const getUsersControllerDisable2FAMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDisable2FA>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerDisable2FA>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerDisable2FA'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerDisable2FA>>,
    void
  > = () => {
    return usersControllerDisable2FA();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerDisable2FAMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerDisable2FA>>
>;

export type UsersControllerDisable2FAMutationError = unknown;

/**
 * @summary Disable two-factor authentication
 */
export const useUsersControllerDisable2FA = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDisable2FA>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerDisable2FA>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerDisable2FAMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete user account
 */
export const usersControllerDeleteAccount = () => {
  return customAxiosInstance<void>({ url: `/api/v1/users/account`, method: 'DELETE' });
};

export const getUsersControllerDeleteAccountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerDeleteAccount'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
    void
  > = () => {
    return usersControllerDeleteAccount();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerDeleteAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerDeleteAccount>>
>;

export type UsersControllerDeleteAccountMutationError = unknown;

/**
 * @summary Delete user account
 */
export const useUsersControllerDeleteAccount = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerDeleteAccountMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get AI settings
 */
export const usersControllerGetAiSettings = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/settings/ai`, method: 'GET', signal });
};

export const getUsersControllerGetAiSettingsQueryKey = () => {
  return [`/api/v1/users/settings/ai`] as const;
};

export const getUsersControllerGetAiSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetAiSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAiSettings>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetAiSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetAiSettings>>> = ({
    signal,
  }) => usersControllerGetAiSettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAiSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetAiSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetAiSettings>>
>;
export type UsersControllerGetAiSettingsQueryError = unknown;

/**
 * @summary Get AI settings
 */

export function useUsersControllerGetAiSettings<
  TData = Awaited<ReturnType<typeof usersControllerGetAiSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetAiSettings>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetAiSettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update AI settings
 */
export const usersControllerUpdateAiSettings = (updateAiSettingsDtoDTO: UpdateAiSettingsDtoDTO) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/ai`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAiSettingsDtoDTO,
  });
};

export const getUsersControllerUpdateAiSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateAiSettings>>,
    TError,
    { data: UpdateAiSettingsDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateAiSettings>>,
  TError,
  { data: UpdateAiSettingsDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateAiSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateAiSettings>>,
    { data: UpdateAiSettingsDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdateAiSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateAiSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateAiSettings>>
>;
export type UsersControllerUpdateAiSettingsMutationBody = UpdateAiSettingsDtoDTO;
export type UsersControllerUpdateAiSettingsMutationError = unknown;

/**
 * @summary Update AI settings
 */
export const useUsersControllerUpdateAiSettings = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateAiSettings>>,
    TError,
    { data: UpdateAiSettingsDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateAiSettings>>,
  TError,
  { data: UpdateAiSettingsDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateAiSettingsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get scheduling settings
 */
export const usersControllerGetSchedulingSettings = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/scheduling`,
    method: 'GET',
    signal,
  });
};

export const getUsersControllerGetSchedulingSettingsQueryKey = () => {
  return [`/api/v1/users/settings/scheduling`] as const;
};

export const getUsersControllerGetSchedulingSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetSchedulingSettingsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>
  > = ({ signal }) => usersControllerGetSchedulingSettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetSchedulingSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>
>;
export type UsersControllerGetSchedulingSettingsQueryError = unknown;

/**
 * @summary Get scheduling settings
 */

export function useUsersControllerGetSchedulingSettings<
  TData = Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetSchedulingSettings>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetSchedulingSettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update scheduling settings
 */
export const usersControllerUpdateSchedulingSettings = (
  updateSchedulingSettingsDtoDTO: UpdateSchedulingSettingsDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/scheduling`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateSchedulingSettingsDtoDTO,
  });
};

export const getUsersControllerUpdateSchedulingSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateSchedulingSettings>>,
    TError,
    { data: UpdateSchedulingSettingsDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateSchedulingSettings>>,
  TError,
  { data: UpdateSchedulingSettingsDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateSchedulingSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateSchedulingSettings>>,
    { data: UpdateSchedulingSettingsDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdateSchedulingSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateSchedulingSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateSchedulingSettings>>
>;
export type UsersControllerUpdateSchedulingSettingsMutationBody = UpdateSchedulingSettingsDtoDTO;
export type UsersControllerUpdateSchedulingSettingsMutationError = unknown;

/**
 * @summary Update scheduling settings
 */
export const useUsersControllerUpdateSchedulingSettings = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateSchedulingSettings>>,
    TError,
    { data: UpdateSchedulingSettingsDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateSchedulingSettings>>,
  TError,
  { data: UpdateSchedulingSettingsDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateSchedulingSettingsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get analytics settings
 */
export const usersControllerGetAnalyticsSettings = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/analytics`,
    method: 'GET',
    signal,
  });
};

export const getUsersControllerGetAnalyticsSettingsQueryKey = () => {
  return [`/api/v1/users/settings/analytics`] as const;
};

export const getUsersControllerGetAnalyticsSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetAnalyticsSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>> = ({
    signal,
  }) => usersControllerGetAnalyticsSettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetAnalyticsSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>
>;
export type UsersControllerGetAnalyticsSettingsQueryError = unknown;

/**
 * @summary Get analytics settings
 */

export function useUsersControllerGetAnalyticsSettings<
  TData = Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAnalyticsSettings>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetAnalyticsSettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update analytics settings
 */
export const usersControllerUpdateAnalyticsSettings = (
  updateAnalyticsSettingsDtoDTO: UpdateAnalyticsSettingsDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/analytics`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAnalyticsSettingsDtoDTO,
  });
};

export const getUsersControllerUpdateAnalyticsSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateAnalyticsSettings>>,
    TError,
    { data: UpdateAnalyticsSettingsDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateAnalyticsSettings>>,
  TError,
  { data: UpdateAnalyticsSettingsDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateAnalyticsSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateAnalyticsSettings>>,
    { data: UpdateAnalyticsSettingsDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdateAnalyticsSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateAnalyticsSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateAnalyticsSettings>>
>;
export type UsersControllerUpdateAnalyticsSettingsMutationBody = UpdateAnalyticsSettingsDtoDTO;
export type UsersControllerUpdateAnalyticsSettingsMutationError = unknown;

/**
 * @summary Update analytics settings
 */
export const useUsersControllerUpdateAnalyticsSettings = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateAnalyticsSettings>>,
    TError,
    { data: UpdateAnalyticsSettingsDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateAnalyticsSettings>>,
  TError,
  { data: UpdateAnalyticsSettingsDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateAnalyticsSettingsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get privacy settings
 */
export const usersControllerGetPrivacySettings = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/privacy`,
    method: 'GET',
    signal,
  });
};

export const getUsersControllerGetPrivacySettingsQueryKey = () => {
  return [`/api/v1/users/settings/privacy`] as const;
};

export const getUsersControllerGetPrivacySettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetPrivacySettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>> = ({
    signal,
  }) => usersControllerGetPrivacySettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetPrivacySettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>
>;
export type UsersControllerGetPrivacySettingsQueryError = unknown;

/**
 * @summary Get privacy settings
 */

export function useUsersControllerGetPrivacySettings<
  TData = Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetPrivacySettings>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetPrivacySettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update privacy settings
 */
export const usersControllerUpdatePrivacySettings = (
  updatePrivacySettingsDtoDTO: UpdatePrivacySettingsDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/privacy`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updatePrivacySettingsDtoDTO,
  });
};

export const getUsersControllerUpdatePrivacySettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdatePrivacySettings>>,
    TError,
    { data: UpdatePrivacySettingsDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdatePrivacySettings>>,
  TError,
  { data: UpdatePrivacySettingsDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdatePrivacySettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdatePrivacySettings>>,
    { data: UpdatePrivacySettingsDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdatePrivacySettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdatePrivacySettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdatePrivacySettings>>
>;
export type UsersControllerUpdatePrivacySettingsMutationBody = UpdatePrivacySettingsDtoDTO;
export type UsersControllerUpdatePrivacySettingsMutationError = unknown;

/**
 * @summary Update privacy settings
 */
export const useUsersControllerUpdatePrivacySettings = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdatePrivacySettings>>,
    TError,
    { data: UpdatePrivacySettingsDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdatePrivacySettings>>,
  TError,
  { data: UpdatePrivacySettingsDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdatePrivacySettingsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get advanced settings
 */
export const usersControllerGetAdvancedSettings = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/advanced`,
    method: 'GET',
    signal,
  });
};

export const getUsersControllerGetAdvancedSettingsQueryKey = () => {
  return [`/api/v1/users/settings/advanced`] as const;
};

export const getUsersControllerGetAdvancedSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetAdvancedSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>> = ({
    signal,
  }) => usersControllerGetAdvancedSettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetAdvancedSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>
>;
export type UsersControllerGetAdvancedSettingsQueryError = unknown;

/**
 * @summary Get advanced settings
 */

export function useUsersControllerGetAdvancedSettings<
  TData = Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAdvancedSettings>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetAdvancedSettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update advanced settings
 */
export const usersControllerUpdateAdvancedSettings = (
  updateAdvancedSettingsDtoDTO: UpdateAdvancedSettingsDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/users/settings/advanced`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updateAdvancedSettingsDtoDTO,
  });
};

export const getUsersControllerUpdateAdvancedSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateAdvancedSettings>>,
    TError,
    { data: UpdateAdvancedSettingsDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateAdvancedSettings>>,
  TError,
  { data: UpdateAdvancedSettingsDtoDTO },
  TContext
> => {
  const mutationKey = ['usersControllerUpdateAdvancedSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateAdvancedSettings>>,
    { data: UpdateAdvancedSettingsDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return usersControllerUpdateAdvancedSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateAdvancedSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateAdvancedSettings>>
>;
export type UsersControllerUpdateAdvancedSettingsMutationBody = UpdateAdvancedSettingsDtoDTO;
export type UsersControllerUpdateAdvancedSettingsMutationError = unknown;

/**
 * @summary Update advanced settings
 */
export const useUsersControllerUpdateAdvancedSettings = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateAdvancedSettings>>,
    TError,
    { data: UpdateAdvancedSettingsDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateAdvancedSettings>>,
  TError,
  { data: UpdateAdvancedSettingsDtoDTO },
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateAdvancedSettingsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Reset all settings to defaults
 */
export const usersControllerResetAllSettings = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/settings/reset`, method: 'POST', signal });
};

export const getUsersControllerResetAllSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerResetAllSettings>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerResetAllSettings>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerResetAllSettings'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerResetAllSettings>>,
    void
  > = () => {
    return usersControllerResetAllSettings();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerResetAllSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerResetAllSettings>>
>;

export type UsersControllerResetAllSettingsMutationError = unknown;

/**
 * @summary Reset all settings to defaults
 */
export const useUsersControllerResetAllSettings = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerResetAllSettings>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerResetAllSettings>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerResetAllSettingsMutationOptions(options);

  return useMutation(mutationOptions);
};
