/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get current user subscription
 */
export const subscriptionsControllerGetMySubscription = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/subscriptions/my-subscription`,
    method: 'GET',
    signal,
  });
};

export const getSubscriptionsControllerGetMySubscriptionQueryKey = () => {
  return [`/api/v1/subscriptions/my-subscription`] as const;
};

export const getSubscriptionsControllerGetMySubscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSubscriptionsControllerGetMySubscriptionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>
  > = ({ signal }) => subscriptionsControllerGetMySubscription(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SubscriptionsControllerGetMySubscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>
>;
export type SubscriptionsControllerGetMySubscriptionQueryError = unknown;

/**
 * @summary Get current user subscription
 */

export function useSubscriptionsControllerGetMySubscription<
  TData = Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof subscriptionsControllerGetMySubscription>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSubscriptionsControllerGetMySubscriptionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Upgrade subscription plan
 */
export const subscriptionsControllerUpgradePlan = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/subscriptions/upgrade`,
    method: 'POST',
    signal,
  });
};

export const getSubscriptionsControllerUpgradePlanMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscriptionsControllerUpgradePlan>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscriptionsControllerUpgradePlan>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['subscriptionsControllerUpgradePlan'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscriptionsControllerUpgradePlan>>,
    void
  > = () => {
    return subscriptionsControllerUpgradePlan();
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscriptionsControllerUpgradePlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionsControllerUpgradePlan>>
>;

export type SubscriptionsControllerUpgradePlanMutationError = unknown;

/**
 * @summary Upgrade subscription plan
 */
export const useSubscriptionsControllerUpgradePlan = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscriptionsControllerUpgradePlan>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof subscriptionsControllerUpgradePlan>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSubscriptionsControllerUpgradePlanMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Cancel subscription
 */
export const subscriptionsControllerCancelSubscription = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/subscriptions/cancel`, method: 'POST', signal });
};

export const getSubscriptionsControllerCancelSubscriptionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscriptionsControllerCancelSubscription>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscriptionsControllerCancelSubscription>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['subscriptionsControllerCancelSubscription'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscriptionsControllerCancelSubscription>>,
    void
  > = () => {
    return subscriptionsControllerCancelSubscription();
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscriptionsControllerCancelSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionsControllerCancelSubscription>>
>;

export type SubscriptionsControllerCancelSubscriptionMutationError = unknown;

/**
 * @summary Cancel subscription
 */
export const useSubscriptionsControllerCancelSubscription = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscriptionsControllerCancelSubscription>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof subscriptionsControllerCancelSubscription>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSubscriptionsControllerCancelSubscriptionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Check if user has access to a feature
 */
export const subscriptionsControllerCheckFeatureAccess = (
  feature: string,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/subscriptions/feature/${feature}`,
    method: 'GET',
    signal,
  });
};

export const getSubscriptionsControllerCheckFeatureAccessQueryKey = (feature?: string) => {
  return [`/api/v1/subscriptions/feature/${feature}`] as const;
};

export const getSubscriptionsControllerCheckFeatureAccessQueryOptions = <
  TData = Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>,
  TError = unknown,
>(
  feature: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSubscriptionsControllerCheckFeatureAccessQueryKey(feature);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>
  > = ({ signal }) => subscriptionsControllerCheckFeatureAccess(feature, signal);

  return { queryKey, queryFn, enabled: !!feature, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SubscriptionsControllerCheckFeatureAccessQueryResult = NonNullable<
  Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>
>;
export type SubscriptionsControllerCheckFeatureAccessQueryError = unknown;

/**
 * @summary Check if user has access to a feature
 */

export function useSubscriptionsControllerCheckFeatureAccess<
  TData = Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>,
  TError = unknown,
>(
  feature: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof subscriptionsControllerCheckFeatureAccess>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSubscriptionsControllerCheckFeatureAccessQueryOptions(feature, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
