/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { AnalyticsControllerGetPlatformsRange } from './analyticsControllerGetPlatformsRange';

export type AnalyticsControllerGetPlatformsParams = {
  /**
   * Date range for analytics
   */
  range?: AnalyticsControllerGetPlatformsRange;
};
