/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { AnalyticsControllerGetEngagementRange } from './analyticsControllerGetEngagementRange';

export type AnalyticsControllerGetEngagementParams = {
  /**
   * Date range for analytics
   */
  range?: AnalyticsControllerGetEngagementRange;
};
