/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type AnalyticsControllerGetEngagementRange =
  (typeof AnalyticsControllerGetEngagementRange)[keyof typeof AnalyticsControllerGetEngagementRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnalyticsControllerGetEngagementRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
} as const;
