/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { CompleteOnboardingDtoDTOBusinessType } from './completeOnboardingDtoDTOBusinessType';

export interface CompleteOnboardingDtoDTO {
  /** Business name */
  businessName: string;
  /** Type of business */
  businessType: CompleteOnboardingDtoDTOBusinessType;
  /** Content goals for the business */
  goals: string[];
}
