/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type ContentControllerFindAllStatusesItem =
  (typeof ContentControllerFindAllStatusesItem)[keyof typeof ContentControllerFindAllStatusesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentControllerFindAllStatusesItem = {
  draft: 'draft',
  scheduled: 'scheduled',
  published: 'published',
  failed: 'failed',
} as const;
