/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type ContentControllerFindAllSortBy =
  (typeof ContentControllerFindAllSortBy)[keyof typeof ContentControllerFindAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentControllerFindAllSortBy = {
  createdAt: 'createdAt',
  scheduledFor: 'scheduledFor',
  publishedAt: 'publishedAt',
} as const;
