/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { ContentControllerFindAllPlatformsItem } from './contentControllerFindAllPlatformsItem';
import type { ContentControllerFindAllStatusesItem } from './contentControllerFindAllStatusesItem';
import type { ContentControllerFindAllSortBy } from './contentControllerFindAllSortBy';
import type { ContentControllerFindAllSortOrder } from './contentControllerFindAllSortOrder';

export type ContentControllerFindAllParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Items per page
   */
  limit?: number;
  /**
   * Search in caption
   */
  search?: string;
  /**
   * Filter by platforms
   */
  platforms?: ContentControllerFindAllPlatformsItem[];
  /**
   * Filter by status
   */
  statuses?: ContentControllerFindAllStatusesItem[];
  /**
   * Filter by date from (ISO 8601)
   */
  dateFrom?: string;
  /**
   * Filter by date to (ISO 8601)
   */
  dateTo?: string;
  /**
   * Sort by field
   */
  sortBy?: ContentControllerFindAllSortBy;
  /**
   * Sort order
   */
  sortOrder?: ContentControllerFindAllSortOrder;
};
