/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Content language
 */
export type CreateContentDtoDTOLanguage =
  (typeof CreateContentDtoDTOLanguage)[keyof typeof CreateContentDtoDTOLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateContentDtoDTOLanguage = {
  english: 'english',
  hindi: 'hindi',
  hinglish: 'hinglish',
} as const;
