/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Content marketing goal
 */
export type CreateContentDtoDTOContentGoal =
  (typeof CreateContentDtoDTOContentGoal)[keyof typeof CreateContentDtoDTOContentGoal];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateContentDtoDTOContentGoal = {
  promotion: 'promotion',
  awareness: 'awareness',
  engagement: 'engagement',
  festival: 'festival',
  offer: 'offer',
} as const;
