/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Social media platform
 */
export type CreateContentDtoDTOPlatform =
  (typeof CreateContentDtoDTOPlatform)[keyof typeof CreateContentDtoDTOPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateContentDtoDTOPlatform = {
  instagram: 'instagram',
  facebook: 'facebook',
  whatsapp: 'whatsapp',
  'google-business': 'google-business',
} as const;
