/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { CreateContentDtoDTOPlatform } from './createContentDtoDTOPlatform';
import type { CreateContentDtoDTOStatus } from './createContentDtoDTOStatus';
import type { CreateContentDtoDTOBusinessType } from './createContentDtoDTOBusinessType';
import type { CreateContentDtoDTOContentGoal } from './createContentDtoDTOContentGoal';
import type { CreateContentDtoDTOTone } from './createContentDtoDTOTone';
import type { CreateContentDtoDTOLanguage } from './createContentDtoDTOLanguage';
import type { CreateContentDtoDTOVisualStyle } from './createContentDtoDTOVisualStyle';
import type { CreateContentDtoDTOEngagement } from './createContentDtoDTOEngagement';

export interface CreateContentDtoDTO {
  /** Content caption/text */
  caption: string;
  /** Hashtags */
  hashtags: string[];
  /** Social media platform */
  platform: CreateContentDtoDTOPlatform;
  /** Content status */
  status?: CreateContentDtoDTOStatus;
  /** Business type */
  businessType?: CreateContentDtoDTOBusinessType;
  /** Content marketing goal */
  contentGoal?: CreateContentDtoDTOContentGoal;
  /** Content tone */
  tone?: CreateContentDtoDTOTone;
  /** Content language */
  language?: CreateContentDtoDTOLanguage;
  /** Visual style preference */
  visualStyle?: CreateContentDtoDTOVisualStyle;
  /** Scheduled date and time (ISO 8601) */
  scheduledFor?: string;
  /** Media URLs */
  mediaUrls?: string[];
  /** AI tags */
  aiTags?: string[];
  /** AI idea ID reference */
  aiIdeaId?: string;
  /** Organization ID (for team accounts) */
  organizationId?: number;
  /** Engagement metrics */
  engagement?: CreateContentDtoDTOEngagement;
}
