/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Visual style preference
 */
export type CreateContentDtoDTOVisualStyle =
  (typeof CreateContentDtoDTOVisualStyle)[keyof typeof CreateContentDtoDTOVisualStyle];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateContentDtoDTOVisualStyle = {
  clean: 'clean',
  festive: 'festive',
  modern: 'modern',
  bold: 'bold',
} as const;
