/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Business type
 */
export type CreateContentDtoDTOBusinessType =
  (typeof CreateContentDtoDTOBusinessType)[keyof typeof CreateContentDtoDTOBusinessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateContentDtoDTOBusinessType = {
  cafe: 'cafe',
  kirana: 'kirana',
  salon: 'salon',
  gym: 'gym',
  clinic: 'clinic',
  restaurant: 'restaurant',
  boutique: 'boutique',
  'tea-shop': 'tea-shop',
} as const;
