/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export interface GeneratePlanDtoDTO {
  /** Plan type: weekly or monthly */
  type: string;
  startDate?: string;
}
