/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { MediaAssetsControllerFindAllAssetType } from './mediaAssetsControllerFindAllAssetType';
import type { MediaAssetsControllerFindAllCategory } from './mediaAssetsControllerFindAllCategory';

export type MediaAssetsControllerFindAllParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  assetType?: MediaAssetsControllerFindAllAssetType;
  category?: MediaAssetsControllerFindAllCategory;
  relatedEntityType?: string;
  relatedEntityId?: number;
  search?: string;
};
