/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type MediaAssetsControllerFindAllCategory =
  (typeof MediaAssetsControllerFindAllCategory)[keyof typeof MediaAssetsControllerFindAllCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaAssetsControllerFindAllCategory = {
  avatar: 'avatar',
  content_media: 'content_media',
  badge_icon: 'badge_icon',
  achievement_icon: 'achievement_icon',
  festival_banner: 'festival_banner',
  brand_asset: 'brand_asset',
  ai_generated: 'ai_generated',
  system_icon: 'system_icon',
  template_visual: 'template_visual',
  platform_asset: 'platform_asset',
} as const;
