/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type MediaAssetsControllerFindAllAssetType =
  (typeof MediaAssetsControllerFindAllAssetType)[keyof typeof MediaAssetsControllerFindAllAssetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaAssetsControllerFindAllAssetType = {
  image: 'image',
  video: 'video',
  audio: 'audio',
  icon: 'icon',
  badge: 'badge',
  banner: 'banner',
  document: 'document',
} as const;
