/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { RegisterDtoDTOBusinessType } from './registerDtoDTOBusinessType';

export interface RegisterDtoDTO {
  email: string;
  /** @minLength 8 */
  password: string;
  name: string;
  businessName?: string;
  businessType?: RegisterDtoDTOBusinessType;
  /** Content goals: awareness, engagement, promotion, festival */
  goals?: string[];
}
