/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type RegisterDtoDTOBusinessType =
  (typeof RegisterDtoDTOBusinessType)[keyof typeof RegisterDtoDTOBusinessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDtoDTOBusinessType = {
  cafe: 'cafe',
  kirana: 'kirana',
  salon: 'salon',
  gym: 'gym',
  clinic: 'clinic',
  restaurant: 'restaurant',
  boutique: 'boutique',
  'tea-shop': 'tea-shop',
} as const;
