/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type TemplateLibraryControllerFindAllCategory =
  (typeof TemplateLibraryControllerFindAllCategory)[keyof typeof TemplateLibraryControllerFindAllCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TemplateLibraryControllerFindAllCategory = {
  festival: 'festival',
  promotion: 'promotion',
  engagement: 'engagement',
  seasonal: 'seasonal',
  industry: 'industry',
  milestone: 'milestone',
} as const;
