/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type TemplateLibraryControllerFindAllRegion =
  (typeof TemplateLibraryControllerFindAllRegion)[keyof typeof TemplateLibraryControllerFindAllRegion];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TemplateLibraryControllerFindAllRegion = {
  north_india: 'north_india',
  south_india: 'south_india',
  east_india: 'east_india',
  west_india: 'west_india',
  central_india: 'central_india',
  pan_india: 'pan_india',
} as const;
