/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { TemplateLibraryControllerFindAllCategory } from './templateLibraryControllerFindAllCategory';
import type { TemplateLibraryControllerFindAllRegion } from './templateLibraryControllerFindAllRegion';

export type TemplateLibraryControllerFindAllParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Items per page
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  category?: TemplateLibraryControllerFindAllCategory;
  businessType?: string;
  language?: string;
  platform?: string;
  region?: TemplateLibraryControllerFindAllRegion;
  search?: string;
  tone?: string;
};
