/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdatePreferencesDtoDTOLanguage } from './updatePreferencesDtoDTOLanguage';
import type { UpdatePreferencesDtoDTOTone } from './updatePreferencesDtoDTOTone';

export interface UpdatePreferencesDtoDTO {
  /** Default language */
  language?: UpdatePreferencesDtoDTOLanguage;
  /** Default tone */
  tone?: UpdatePreferencesDtoDTOTone;
  /** Auto-save drafts */
  autoSave?: boolean;
  /** Dark mode enabled */
  darkMode?: boolean;
}
