/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdateAdvancedSettingsDtoDTOImageQuality } from './updateAdvancedSettingsDtoDTOImageQuality';

export interface UpdateAdvancedSettingsDtoDTO {
  debugMode?: boolean;
  apiLogs?: boolean;
  betaFeatures?: boolean;
  aiModelTesting?: boolean;
  imageQuality?: UpdateAdvancedSettingsDtoDTOImageQuality;
  /** Cache duration in days */
  cacheDuration?: number;
}
