/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Default language
 */
export type UpdatePreferencesDtoDTOLanguage =
  (typeof UpdatePreferencesDtoDTOLanguage)[keyof typeof UpdatePreferencesDtoDTOLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePreferencesDtoDTOLanguage = {
  english: 'english',
  hindi: 'hindi',
  hinglish: 'hinglish',
} as const;
