/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export interface UpdateNotificationsDtoDTO {
  /** Email notifications enabled */
  email?: boolean;
  /** Push notifications enabled */
  push?: boolean;
  /** Content ready notifications */
  contentReady?: boolean;
  /** Weekly report notifications */
  weeklyReport?: boolean;
  /** AI suggestions notifications */
  aiSuggestions?: boolean;
}
