/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Visual style preference
 */
export type UpdateContentDtoDTOVisualStyle =
  (typeof UpdateContentDtoDTOVisualStyle)[keyof typeof UpdateContentDtoDTOVisualStyle];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateContentDtoDTOVisualStyle = {
  clean: 'clean',
  festive: 'festive',
  modern: 'modern',
  bold: 'bold',
} as const;
