/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdateContentDtoDTOPlatform } from './updateContentDtoDTOPlatform';
import type { UpdateContentDtoDTOStatus } from './updateContentDtoDTOStatus';
import type { UpdateContentDtoDTOBusinessType } from './updateContentDtoDTOBusinessType';
import type { UpdateContentDtoDTOContentGoal } from './updateContentDtoDTOContentGoal';
import type { UpdateContentDtoDTOTone } from './updateContentDtoDTOTone';
import type { UpdateContentDtoDTOLanguage } from './updateContentDtoDTOLanguage';
import type { UpdateContentDtoDTOVisualStyle } from './updateContentDtoDTOVisualStyle';
import type { UpdateContentDtoDTOEngagement } from './updateContentDtoDTOEngagement';

export interface UpdateContentDtoDTO {
  /** Content caption/text */
  caption?: string;
  /** Hashtags */
  hashtags?: string[];
  /** Social media platform */
  platform?: UpdateContentDtoDTOPlatform;
  /** Content status */
  status?: UpdateContentDtoDTOStatus;
  /** Business type */
  businessType?: UpdateContentDtoDTOBusinessType;
  /** Content marketing goal */
  contentGoal?: UpdateContentDtoDTOContentGoal;
  /** Content tone */
  tone?: UpdateContentDtoDTOTone;
  /** Content language */
  language?: UpdateContentDtoDTOLanguage;
  /** Visual style preference */
  visualStyle?: UpdateContentDtoDTOVisualStyle;
  /** Scheduled date and time (ISO 8601) */
  scheduledFor?: string;
  /** Media URLs */
  mediaUrls?: string[];
  /** AI tags */
  aiTags?: string[];
  /** AI idea ID reference */
  aiIdeaId?: string;
  /** Organization ID (for team accounts) */
  organizationId?: number;
  /** Engagement metrics */
  engagement?: UpdateContentDtoDTOEngagement;
}
