/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type UpdateAnalyticsSettingsDtoDTOWeeklyReportDay =
  (typeof UpdateAnalyticsSettingsDtoDTOWeeklyReportDay)[keyof typeof UpdateAnalyticsSettingsDtoDTOWeeklyReportDay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAnalyticsSettingsDtoDTOWeeklyReportDay = {
  monday: 'monday',
  tuesday: 'tuesday',
  wednesday: 'wednesday',
  thursday: 'thursday',
  friday: 'friday',
  saturday: 'saturday',
  sunday: 'sunday',
} as const;
