/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type UpdateAiSettingsDtoDTOCaptionLength =
  (typeof UpdateAiSettingsDtoDTOCaptionLength)[keyof typeof UpdateAiSettingsDtoDTOCaptionLength];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAiSettingsDtoDTOCaptionLength = {
  short: 'short',
  medium: 'medium',
  long: 'long',
} as const;
