/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdateSchedulingSettingsDtoDTOPostingSchedule } from './updateSchedulingSettingsDtoDTOPostingSchedule';

export interface UpdateSchedulingSettingsDtoDTO {
  autoScheduling?: boolean;
  optimizeTiming?: boolean;
  minBuffer?: number;
  maxPostsPerDay?: number;
  /** Posting schedule by day */
  postingSchedule?: UpdateSchedulingSettingsDtoDTOPostingSchedule;
}
