/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type UpdateAiSettingsDtoDTOAiPriority =
  (typeof UpdateAiSettingsDtoDTOAiPriority)[keyof typeof UpdateAiSettingsDtoDTOAiPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAiSettingsDtoDTOAiPriority = {
  speed: 'speed',
  balanced: 'balanced',
  quality: 'quality',
} as const;
