/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

/**
 * Default tone
 */
export type UpdatePreferencesDtoDTOTone =
  (typeof UpdatePreferencesDtoDTOTone)[keyof typeof UpdatePreferencesDtoDTOTone];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePreferencesDtoDTOTone = {
  friendly: 'friendly',
  professional: 'professional',
  fun: 'fun',
  minimal: 'minimal',
} as const;
