/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type UpdatePrivacySettingsDtoDTOProfileVisibility =
  (typeof UpdatePrivacySettingsDtoDTOProfileVisibility)[keyof typeof UpdatePrivacySettingsDtoDTOProfileVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePrivacySettingsDtoDTOProfileVisibility = {
  public: 'public',
  team: 'team',
  private: 'private',
} as const;
