/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export type UpdateAdvancedSettingsDtoDTOImageQuality =
  (typeof UpdateAdvancedSettingsDtoDTOImageQuality)[keyof typeof UpdateAdvancedSettingsDtoDTOImageQuality];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdvancedSettingsDtoDTOImageQuality = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  original: 'original',
} as const;
