/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdateAiSettingsDtoDTOAiPriority } from './updateAiSettingsDtoDTOAiPriority';
import type { UpdateAiSettingsDtoDTOVisualStyle } from './updateAiSettingsDtoDTOVisualStyle';
import type { UpdateAiSettingsDtoDTOCaptionLength } from './updateAiSettingsDtoDTOCaptionLength';
import type { UpdateAiSettingsDtoDTOEmojiUsage } from './updateAiSettingsDtoDTOEmojiUsage';

export interface UpdateAiSettingsDtoDTO {
  aiPriority?: UpdateAiSettingsDtoDTOAiPriority;
  autoEnhance?: boolean;
  smartHashtags?: boolean;
  contentNotifications?: boolean;
  experimentalFeatures?: boolean;
  visualStyle?: UpdateAiSettingsDtoDTOVisualStyle;
  captionLength?: UpdateAiSettingsDtoDTOCaptionLength;
  emojiUsage?: UpdateAiSettingsDtoDTOEmojiUsage;
}
