/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdateAnalyticsSettingsDtoDTOWeeklyReportDay } from './updateAnalyticsSettingsDtoDTOWeeklyReportDay';

export interface UpdateAnalyticsSettingsDtoDTO {
  weeklyReportDay?: UpdateAnalyticsSettingsDtoDTOWeeklyReportDay;
  includeReach?: boolean;
  includeEngagement?: boolean;
  includeGrowth?: boolean;
  includeTopPosts?: boolean;
  trackClicks?: boolean;
  trackVisits?: boolean;
  trackDemographics?: boolean;
}
