/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export interface UpdateAppSettingDtoDTO {
  /** New value for the setting (always a string, parsed by value_type) */
  value: string;
}
