/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdatePrivacySettingsDtoDTOProfileVisibility } from './updatePrivacySettingsDtoDTOProfileVisibility';
import type { UpdatePrivacySettingsDtoDTOShareAnalytics } from './updatePrivacySettingsDtoDTOShareAnalytics';

export interface UpdatePrivacySettingsDtoDTO {
  storeDrafts?: boolean;
  cacheContent?: boolean;
  analyticsCollection?: boolean;
  profileVisibility?: UpdatePrivacySettingsDtoDTOProfileVisibility;
  shareAnalytics?: UpdatePrivacySettingsDtoDTOShareAnalytics;
}
