/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */

export interface VerifyPhoneOtpDtoDTO {
  /** Phone number with country code */
  phone: string;
  /**
   * 6-digit OTP code
   * @minLength 6
   * @maxLength 6
   */
  otp: string;
}
