/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Active DB health — live ping + metadata
 */
export const appControllerGetHealth = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/health`, method: 'GET', signal });
};

export const getAppControllerGetHealthQueryKey = () => {
  return [`/health`] as const;
};

export const getAppControllerGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetHealth>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHealth>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHealth>>> = ({ signal }) =>
    appControllerGetHealth(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetHealth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerGetHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHealth>>
>;
export type AppControllerGetHealthQueryError = unknown;

/**
 * @summary Active DB health — live ping + metadata
 */

export function useAppControllerGetHealth<
  TData = Awaited<ReturnType<typeof appControllerGetHealth>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHealth>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerGetHealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary All remote DBs health — parallel ping across the registry
 */
export const appControllerGetAllDbsHealth = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/health/all-dbs`, method: 'GET', signal });
};

export const getAppControllerGetAllDbsHealthQueryKey = () => {
  return [`/api/v1/health/all-dbs`] as const;
};

export const getAppControllerGetAllDbsHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetAllDbsHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>> = ({
    signal,
  }) => appControllerGetAllDbsHealth(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerGetAllDbsHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>
>;
export type AppControllerGetAllDbsHealthQueryError = unknown;

/**
 * @summary All remote DBs health — parallel ping across the registry
 */

export function useAppControllerGetAllDbsHealth<
  TData = Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerGetAllDbsHealth>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerGetAllDbsHealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
