/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get full user preferences (regional + learned + rules + streaks)
 */
export const personalizationControllerGetProfile = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/personalization/profile`,
    method: 'GET',
    signal,
  });
};

export const getPersonalizationControllerGetProfileQueryKey = () => {
  return [`/api/v1/personalization/profile`] as const;
};

export const getPersonalizationControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof personalizationControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof personalizationControllerGetProfile>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPersonalizationControllerGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof personalizationControllerGetProfile>>> = ({
    signal,
  }) => personalizationControllerGetProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof personalizationControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PersonalizationControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof personalizationControllerGetProfile>>
>;
export type PersonalizationControllerGetProfileQueryError = unknown;

/**
 * @summary Get full user preferences (regional + learned + rules + streaks)
 */

export function usePersonalizationControllerGetProfile<
  TData = Awaited<ReturnType<typeof personalizationControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof personalizationControllerGetProfile>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPersonalizationControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update regional or manually override a learned preference
 */
export const personalizationControllerUpdateProfile = () => {
  return customAxiosInstance<void>({ url: `/api/v1/personalization/profile`, method: 'PATCH' });
};

export const getPersonalizationControllerUpdateProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalizationControllerUpdateProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof personalizationControllerUpdateProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['personalizationControllerUpdateProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof personalizationControllerUpdateProfile>>,
    void
  > = () => {
    return personalizationControllerUpdateProfile();
  };

  return { mutationFn, ...mutationOptions };
};

export type PersonalizationControllerUpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof personalizationControllerUpdateProfile>>
>;

export type PersonalizationControllerUpdateProfileMutationError = unknown;

/**
 * @summary Update regional or manually override a learned preference
 */
export const usePersonalizationControllerUpdateProfile = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalizationControllerUpdateProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof personalizationControllerUpdateProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPersonalizationControllerUpdateProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Reset a specific learned preference
 */
export const personalizationControllerResetPreference = (key: string) => {
  return customAxiosInstance<void>({
    url: `/api/v1/personalization/profile/${key}`,
    method: 'DELETE',
  });
};

export const getPersonalizationControllerResetPreferenceMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalizationControllerResetPreference>>,
    TError,
    { key: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof personalizationControllerResetPreference>>,
  TError,
  { key: string },
  TContext
> => {
  const mutationKey = ['personalizationControllerResetPreference'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof personalizationControllerResetPreference>>,
    { key: string }
  > = props => {
    const { key } = props ?? {};

    return personalizationControllerResetPreference(key);
  };

  return { mutationFn, ...mutationOptions };
};

export type PersonalizationControllerResetPreferenceMutationResult = NonNullable<
  Awaited<ReturnType<typeof personalizationControllerResetPreference>>
>;

export type PersonalizationControllerResetPreferenceMutationError = unknown;

/**
 * @summary Reset a specific learned preference
 */
export const usePersonalizationControllerResetPreference = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalizationControllerResetPreference>>,
    TError,
    { key: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof personalizationControllerResetPreference>>,
  TError,
  { key: string },
  TContext
> => {
  const mutationOptions = getPersonalizationControllerResetPreferenceMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Enable/disable personalized mode
 */
export const personalizationControllerToggle = () => {
  return customAxiosInstance<void>({ url: `/api/v1/personalization/toggle`, method: 'PATCH' });
};

export const getPersonalizationControllerToggleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalizationControllerToggle>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof personalizationControllerToggle>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['personalizationControllerToggle'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof personalizationControllerToggle>>,
    void
  > = () => {
    return personalizationControllerToggle();
  };

  return { mutationFn, ...mutationOptions };
};

export type PersonalizationControllerToggleMutationResult = NonNullable<
  Awaited<ReturnType<typeof personalizationControllerToggle>>
>;

export type PersonalizationControllerToggleMutationError = unknown;

/**
 * @summary Enable/disable personalized mode
 */
export const usePersonalizationControllerToggle = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalizationControllerToggle>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof personalizationControllerToggle>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPersonalizationControllerToggleMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get signal count breakdown by type
 */
export const personalizationControllerSignalStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/personalization/signals/stats`,
    method: 'GET',
    signal,
  });
};

export const getPersonalizationControllerSignalStatsQueryKey = () => {
  return [`/api/v1/personalization/signals/stats`] as const;
};

export const getPersonalizationControllerSignalStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof personalizationControllerSignalStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof personalizationControllerSignalStats>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPersonalizationControllerSignalStatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof personalizationControllerSignalStats>>
  > = ({ signal }) => personalizationControllerSignalStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof personalizationControllerSignalStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PersonalizationControllerSignalStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof personalizationControllerSignalStats>>
>;
export type PersonalizationControllerSignalStatsQueryError = unknown;

/**
 * @summary Get signal count breakdown by type
 */

export function usePersonalizationControllerSignalStats<
  TData = Awaited<ReturnType<typeof personalizationControllerSignalStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof personalizationControllerSignalStats>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getPersonalizationControllerSignalStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
