/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ContextControllerGetDemoPreviewParams,
  ContextControllerGetTemplatesParams,
  ContextPreviewDtoDTO,
  CreateBusinessProfileDtoDTO,
  CreateMemoryDtoDTO,
  CreateTemplateDtoDTO,
  UpdateBusinessProfileDtoDTO,
  UpdateTemplateDtoDTO,
} from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

export const contextControllerGetBusinessProfile = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/context/profile`, method: 'GET', signal });
};

export const getContextControllerGetBusinessProfileQueryKey = () => {
  return [`/api/v1/context/profile`] as const;
};

export const getContextControllerGetBusinessProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContextControllerGetBusinessProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>> = ({
    signal,
  }) => contextControllerGetBusinessProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContextControllerGetBusinessProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>
>;
export type ContextControllerGetBusinessProfileQueryError = unknown;

export function useContextControllerGetBusinessProfile<
  TData = Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetBusinessProfile>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContextControllerGetBusinessProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const contextControllerCreateBusinessProfile = (
  createBusinessProfileDtoDTO: CreateBusinessProfileDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/profile`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createBusinessProfileDtoDTO,
    signal,
  });
};

export const getContextControllerCreateBusinessProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerCreateBusinessProfile>>,
    TError,
    { data: CreateBusinessProfileDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerCreateBusinessProfile>>,
  TError,
  { data: CreateBusinessProfileDtoDTO },
  TContext
> => {
  const mutationKey = ['contextControllerCreateBusinessProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerCreateBusinessProfile>>,
    { data: CreateBusinessProfileDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return contextControllerCreateBusinessProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerCreateBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerCreateBusinessProfile>>
>;
export type ContextControllerCreateBusinessProfileMutationBody = CreateBusinessProfileDtoDTO;
export type ContextControllerCreateBusinessProfileMutationError = unknown;

export const useContextControllerCreateBusinessProfile = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerCreateBusinessProfile>>,
    TError,
    { data: CreateBusinessProfileDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerCreateBusinessProfile>>,
  TError,
  { data: CreateBusinessProfileDtoDTO },
  TContext
> => {
  const mutationOptions = getContextControllerCreateBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerUpdateBusinessProfile = (
  updateBusinessProfileDtoDTO: UpdateBusinessProfileDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/profile`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateBusinessProfileDtoDTO,
  });
};

export const getContextControllerUpdateBusinessProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerUpdateBusinessProfile>>,
    TError,
    { data: UpdateBusinessProfileDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerUpdateBusinessProfile>>,
  TError,
  { data: UpdateBusinessProfileDtoDTO },
  TContext
> => {
  const mutationKey = ['contextControllerUpdateBusinessProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerUpdateBusinessProfile>>,
    { data: UpdateBusinessProfileDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return contextControllerUpdateBusinessProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerUpdateBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerUpdateBusinessProfile>>
>;
export type ContextControllerUpdateBusinessProfileMutationBody = UpdateBusinessProfileDtoDTO;
export type ContextControllerUpdateBusinessProfileMutationError = unknown;

export const useContextControllerUpdateBusinessProfile = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerUpdateBusinessProfile>>,
    TError,
    { data: UpdateBusinessProfileDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerUpdateBusinessProfile>>,
  TError,
  { data: UpdateBusinessProfileDtoDTO },
  TContext
> => {
  const mutationOptions = getContextControllerUpdateBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerDeleteBusinessProfile = () => {
  return customAxiosInstance<void>({ url: `/api/v1/context/profile`, method: 'DELETE' });
};

export const getContextControllerDeleteBusinessProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerDeleteBusinessProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerDeleteBusinessProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['contextControllerDeleteBusinessProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerDeleteBusinessProfile>>,
    void
  > = () => {
    return contextControllerDeleteBusinessProfile();
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerDeleteBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerDeleteBusinessProfile>>
>;

export type ContextControllerDeleteBusinessProfileMutationError = unknown;

export const useContextControllerDeleteBusinessProfile = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerDeleteBusinessProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerDeleteBusinessProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getContextControllerDeleteBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerGetMemories = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/context/memories`, method: 'GET', signal });
};

export const getContextControllerGetMemoriesQueryKey = () => {
  return [`/api/v1/context/memories`] as const;
};

export const getContextControllerGetMemoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof contextControllerGetMemories>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof contextControllerGetMemories>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContextControllerGetMemoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contextControllerGetMemories>>> = ({
    signal,
  }) => contextControllerGetMemories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetMemories>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContextControllerGetMemoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetMemories>>
>;
export type ContextControllerGetMemoriesQueryError = unknown;

export function useContextControllerGetMemories<
  TData = Awaited<ReturnType<typeof contextControllerGetMemories>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof contextControllerGetMemories>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContextControllerGetMemoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const contextControllerCreateMemory = (
  createMemoryDtoDTO: CreateMemoryDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/memories`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createMemoryDtoDTO,
    signal,
  });
};

export const getContextControllerCreateMemoryMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerCreateMemory>>,
    TError,
    { data: CreateMemoryDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerCreateMemory>>,
  TError,
  { data: CreateMemoryDtoDTO },
  TContext
> => {
  const mutationKey = ['contextControllerCreateMemory'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerCreateMemory>>,
    { data: CreateMemoryDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return contextControllerCreateMemory(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerCreateMemoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerCreateMemory>>
>;
export type ContextControllerCreateMemoryMutationBody = CreateMemoryDtoDTO;
export type ContextControllerCreateMemoryMutationError = unknown;

export const useContextControllerCreateMemory = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerCreateMemory>>,
    TError,
    { data: CreateMemoryDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerCreateMemory>>,
  TError,
  { data: CreateMemoryDtoDTO },
  TContext
> => {
  const mutationOptions = getContextControllerCreateMemoryMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerGetMemoryStats = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/memories/stats`,
    method: 'GET',
    signal,
  });
};

export const getContextControllerGetMemoryStatsQueryKey = () => {
  return [`/api/v1/context/memories/stats`] as const;
};

export const getContextControllerGetMemoryStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof contextControllerGetMemoryStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetMemoryStats>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContextControllerGetMemoryStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contextControllerGetMemoryStats>>> = ({
    signal,
  }) => contextControllerGetMemoryStats(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetMemoryStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContextControllerGetMemoryStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetMemoryStats>>
>;
export type ContextControllerGetMemoryStatsQueryError = unknown;

export function useContextControllerGetMemoryStats<
  TData = Awaited<ReturnType<typeof contextControllerGetMemoryStats>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetMemoryStats>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContextControllerGetMemoryStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const contextControllerDeleteMemory = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/context/memories/${id}`, method: 'DELETE' });
};

export const getContextControllerDeleteMemoryMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerDeleteMemory>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerDeleteMemory>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['contextControllerDeleteMemory'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerDeleteMemory>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return contextControllerDeleteMemory(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerDeleteMemoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerDeleteMemory>>
>;

export type ContextControllerDeleteMemoryMutationError = unknown;

export const useContextControllerDeleteMemory = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerDeleteMemory>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerDeleteMemory>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getContextControllerDeleteMemoryMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerProvideFeedback = (id: number, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/memories/${id}/feedback`,
    method: 'POST',
    signal,
  });
};

export const getContextControllerProvideFeedbackMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerProvideFeedback>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerProvideFeedback>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['contextControllerProvideFeedback'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerProvideFeedback>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return contextControllerProvideFeedback(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerProvideFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerProvideFeedback>>
>;

export type ContextControllerProvideFeedbackMutationError = unknown;

export const useContextControllerProvideFeedback = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerProvideFeedback>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerProvideFeedback>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getContextControllerProvideFeedbackMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerPruneMemories = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/memories/prune`,
    method: 'POST',
    signal,
  });
};

export const getContextControllerPruneMemoriesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerPruneMemories>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerPruneMemories>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['contextControllerPruneMemories'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerPruneMemories>>,
    void
  > = () => {
    return contextControllerPruneMemories();
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerPruneMemoriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerPruneMemories>>
>;

export type ContextControllerPruneMemoriesMutationError = unknown;

export const useContextControllerPruneMemories = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerPruneMemories>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerPruneMemories>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getContextControllerPruneMemoriesMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerGetTemplates = (
  params: ContextControllerGetTemplatesParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/templates`,
    method: 'GET',
    params,
    signal,
  });
};

export const getContextControllerGetTemplatesQueryKey = (
  params?: ContextControllerGetTemplatesParams,
) => {
  return [`/api/v1/context/templates`, ...(params ? [params] : [])] as const;
};

export const getContextControllerGetTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof contextControllerGetTemplates>>,
  TError = unknown,
>(
  params: ContextControllerGetTemplatesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contextControllerGetTemplates>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContextControllerGetTemplatesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contextControllerGetTemplates>>> = ({
    signal,
  }) => contextControllerGetTemplates(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetTemplates>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContextControllerGetTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetTemplates>>
>;
export type ContextControllerGetTemplatesQueryError = unknown;

export function useContextControllerGetTemplates<
  TData = Awaited<ReturnType<typeof contextControllerGetTemplates>>,
  TError = unknown,
>(
  params: ContextControllerGetTemplatesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contextControllerGetTemplates>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContextControllerGetTemplatesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const contextControllerCreateTemplate = (
  createTemplateDtoDTO: CreateTemplateDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/templates`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createTemplateDtoDTO,
    signal,
  });
};

export const getContextControllerCreateTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerCreateTemplate>>,
    TError,
    { data: CreateTemplateDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerCreateTemplate>>,
  TError,
  { data: CreateTemplateDtoDTO },
  TContext
> => {
  const mutationKey = ['contextControllerCreateTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerCreateTemplate>>,
    { data: CreateTemplateDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return contextControllerCreateTemplate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerCreateTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerCreateTemplate>>
>;
export type ContextControllerCreateTemplateMutationBody = CreateTemplateDtoDTO;
export type ContextControllerCreateTemplateMutationError = unknown;

export const useContextControllerCreateTemplate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerCreateTemplate>>,
    TError,
    { data: CreateTemplateDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerCreateTemplate>>,
  TError,
  { data: CreateTemplateDtoDTO },
  TContext
> => {
  const mutationOptions = getContextControllerCreateTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerUpdateTemplate = (
  id: number,
  updateTemplateDtoDTO: UpdateTemplateDtoDTO,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/templates/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateTemplateDtoDTO,
  });
};

export const getContextControllerUpdateTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerUpdateTemplate>>,
    TError,
    { id: number; data: UpdateTemplateDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerUpdateTemplate>>,
  TError,
  { id: number; data: UpdateTemplateDtoDTO },
  TContext
> => {
  const mutationKey = ['contextControllerUpdateTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerUpdateTemplate>>,
    { id: number; data: UpdateTemplateDtoDTO }
  > = props => {
    const { id, data } = props ?? {};

    return contextControllerUpdateTemplate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerUpdateTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerUpdateTemplate>>
>;
export type ContextControllerUpdateTemplateMutationBody = UpdateTemplateDtoDTO;
export type ContextControllerUpdateTemplateMutationError = unknown;

export const useContextControllerUpdateTemplate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerUpdateTemplate>>,
    TError,
    { id: number; data: UpdateTemplateDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerUpdateTemplate>>,
  TError,
  { id: number; data: UpdateTemplateDtoDTO },
  TContext
> => {
  const mutationOptions = getContextControllerUpdateTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerDeleteTemplate = (id: number) => {
  return customAxiosInstance<void>({ url: `/api/v1/context/templates/${id}`, method: 'DELETE' });
};

export const getContextControllerDeleteTemplateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerDeleteTemplate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerDeleteTemplate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['contextControllerDeleteTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerDeleteTemplate>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return contextControllerDeleteTemplate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerDeleteTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerDeleteTemplate>>
>;

export type ContextControllerDeleteTemplateMutationError = unknown;

export const useContextControllerDeleteTemplate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerDeleteTemplate>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerDeleteTemplate>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getContextControllerDeleteTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerGetPlatformContext = (platform: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/platform/${platform}`,
    method: 'GET',
    signal,
  });
};

export const getContextControllerGetPlatformContextQueryKey = (platform?: string) => {
  return [`/api/v1/context/platform/${platform}`] as const;
};

export const getContextControllerGetPlatformContextQueryOptions = <
  TData = Awaited<ReturnType<typeof contextControllerGetPlatformContext>>,
  TError = unknown,
>(
  platform: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contextControllerGetPlatformContext>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getContextControllerGetPlatformContextQueryKey(platform);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contextControllerGetPlatformContext>>> = ({
    signal,
  }) => contextControllerGetPlatformContext(platform, signal);

  return { queryKey, queryFn, enabled: !!platform, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetPlatformContext>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContextControllerGetPlatformContextQueryResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetPlatformContext>>
>;
export type ContextControllerGetPlatformContextQueryError = unknown;

export function useContextControllerGetPlatformContext<
  TData = Awaited<ReturnType<typeof contextControllerGetPlatformContext>>,
  TError = unknown,
>(
  platform: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contextControllerGetPlatformContext>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContextControllerGetPlatformContextQueryOptions(platform, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const contextControllerUpdatePlatformContext = (platform: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/platform/${platform}`,
    method: 'POST',
    signal,
  });
};

export const getContextControllerUpdatePlatformContextMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerUpdatePlatformContext>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerUpdatePlatformContext>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationKey = ['contextControllerUpdatePlatformContext'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerUpdatePlatformContext>>,
    { platform: string }
  > = props => {
    const { platform } = props ?? {};

    return contextControllerUpdatePlatformContext(platform);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerUpdatePlatformContextMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerUpdatePlatformContext>>
>;

export type ContextControllerUpdatePlatformContextMutationError = unknown;

export const useContextControllerUpdatePlatformContext = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerUpdatePlatformContext>>,
    TError,
    { platform: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerUpdatePlatformContext>>,
  TError,
  { platform: string },
  TContext
> => {
  const mutationOptions = getContextControllerUpdatePlatformContextMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerGetContextPreview = (
  contextPreviewDtoDTO: ContextPreviewDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/preview`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: contextPreviewDtoDTO,
    signal,
  });
};

export const getContextControllerGetContextPreviewMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerGetContextPreview>>,
    TError,
    { data: ContextPreviewDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contextControllerGetContextPreview>>,
  TError,
  { data: ContextPreviewDtoDTO },
  TContext
> => {
  const mutationKey = ['contextControllerGetContextPreview'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contextControllerGetContextPreview>>,
    { data: ContextPreviewDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return contextControllerGetContextPreview(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContextControllerGetContextPreviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetContextPreview>>
>;
export type ContextControllerGetContextPreviewMutationBody = ContextPreviewDtoDTO;
export type ContextControllerGetContextPreviewMutationError = unknown;

export const useContextControllerGetContextPreview = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contextControllerGetContextPreview>>,
    TError,
    { data: ContextPreviewDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof contextControllerGetContextPreview>>,
  TError,
  { data: ContextPreviewDtoDTO },
  TContext
> => {
  const mutationOptions = getContextControllerGetContextPreviewMutationOptions(options);

  return useMutation(mutationOptions);
};
export const contextControllerGetDemoPreview = (
  params: ContextControllerGetDemoPreviewParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/context/preview/demo`,
    method: 'GET',
    params,
    signal,
  });
};

export const getContextControllerGetDemoPreviewQueryKey = (
  params?: ContextControllerGetDemoPreviewParams,
) => {
  return [`/api/v1/context/preview/demo`, ...(params ? [params] : [])] as const;
};

export const getContextControllerGetDemoPreviewQueryOptions = <
  TData = Awaited<ReturnType<typeof contextControllerGetDemoPreview>>,
  TError = unknown,
>(
  params: ContextControllerGetDemoPreviewParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contextControllerGetDemoPreview>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContextControllerGetDemoPreviewQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contextControllerGetDemoPreview>>> = ({
    signal,
  }) => contextControllerGetDemoPreview(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contextControllerGetDemoPreview>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ContextControllerGetDemoPreviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof contextControllerGetDemoPreview>>
>;
export type ContextControllerGetDemoPreviewQueryError = unknown;

export function useContextControllerGetDemoPreview<
  TData = Awaited<ReturnType<typeof contextControllerGetDemoPreview>>,
  TError = unknown,
>(
  params: ContextControllerGetDemoPreviewParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof contextControllerGetDemoPreview>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getContextControllerGetDemoPreviewQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
